-- GENERATED by scripts/gen-views.ts from apps/server/src/db/audience.ts. Do not edit:
-- change the generator and run it again (CI fails on a difference).
--
-- A view pair added after the first views migration (which never changes once
-- applied), with the same rules: security_barrier, granted to its family only.

-- migrate:up
CREATE VIEW pub_meta WITH (security_barrier = true) AS
SELECT (SELECT (m.value #>> '{}')::timestamptz FROM app_meta m WHERE m.key = 'data_epoch') AS data_epoch,
       (SELECT (m.value #>> '{}')::timestamptz FROM app_meta m WHERE m.key = 'display_start') AS display_start;

CREATE VIEW own_meta WITH (security_barrier = true) AS
SELECT (SELECT (m.value #>> '{}')::timestamptz FROM app_meta m WHERE m.key = 'data_epoch') AS data_epoch,
       (SELECT (m.value #>> '{}')::timestamptz FROM app_meta m WHERE m.key = 'display_start') AS display_start;

GRANT SELECT ON pub_meta TO rws_api, rws_publish;
GRANT SELECT ON own_meta TO rws_owner_api;

-- migrate:down
DROP VIEW own_meta;
DROP VIEW pub_meta;
