-- GENERATED by scripts/gen-views.ts from apps/server/src/db/audience.ts. Do not edit:
-- change the generator and run it again (CI fails on a difference).
--
-- security_barrier views, and the two "at T" functions at the end, are the only
-- things a login role may read (A§6). The
-- audience filter is applied at EVERY join: a series by its effective audience,
-- a reference, class, forecast run, warning or attribution also by its own
-- source, a station only with a visible series. pub_* keeps public rows, own_*
-- public and owner rows, neither ever an "off" row; both keep role primary only.

-- migrate:up
-- The effective audience and licence channels of every series: its source's
-- values, narrowed by the series (public > owner > off; a channel stays on only
-- if both allow it). Internal: granted to no login role.
CREATE VIEW series_eff AS
SELECT s.id AS series_id, s.station_id, s.source_id, s.role,
       LEAST(src.audience, COALESCE(s.audience, src.audience)) AS audience,
       src.lic_display        AND COALESCE((s.lic_override ->> 'display')::boolean, true)        AS lic_display,
       src.lic_api            AND COALESCE((s.lic_override ->> 'api')::boolean, true)            AS lic_api,
       src.lic_bulk_export    AND COALESCE((s.lic_override ->> 'bulk_export')::boolean, true)    AS lic_bulk_export,
       src.lic_history_export AND COALESCE((s.lic_override ->> 'history_export')::boolean, true) AS lic_history_export,
       src.history_window
FROM series s
JOIN source src ON src.id = s.source_id;

CREATE VIEW pub_station WITH (security_barrier = true) AS
SELECT st.id, st.name, st.water_name, st.country, st.lon, st.lat, st.river_id, st.reach_id, st.km_official,
       st.km_system, st.km_to_nl_entry, st.nl_entry_node, st.flags, st.tier
FROM station st
WHERE EXISTS (SELECT 1 FROM series_eff e WHERE e.station_id = st.id AND e.audience IN ('public') AND e.role = 'primary' AND e.lic_display);

CREATE VIEW pub_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display;

CREATE VIEW pub_obs WITH (security_barrier = true) AS
SELECT o.series_id, o.ts, o.value, o.qc
FROM obs o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window);

CREATE VIEW pub_obs_latest WITH (security_barrier = true) AS
SELECT o.series_id, o.ts, o.value, o.qc
FROM obs_latest o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window);

CREATE VIEW pub_obs_1h WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1h o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW pub_obs_1d WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1d o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW pub_reference WITH (security_barrier = true) AS
SELECT r.series_id, r.source_id, r.kind, r.value, r.unit, r.semantics, r.percentile_convention, r.period,
       r.season_from_md, r.season_to_md, r.priority, r.basis_label, r.valid
FROM reference_value r
JOIN series_eff e ON e.series_id = r.series_id
JOIN source rs ON rs.id = r.source_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
  AND rs.audience IN ('public') AND rs.lic_display;

CREATE VIEW pub_class WITH (security_barrier = true) AS
SELECT c.subject_type, c.subject_id, c.ts, c.source_id, c.provider_code, c.provider_label, c.level_norm
FROM class_obs c
JOIN source cs ON cs.id = c.source_id
WHERE cs.audience IN ('public') AND cs.lic_display
  AND (c.subject_type = 'area'
       OR EXISTS (SELECT 1 FROM series_eff e WHERE e.station_id = c.subject_id AND e.audience IN ('public') AND e.role = 'primary' AND e.lic_display));

CREATE VIEW pub_forecast_run WITH (security_barrier = true) AS
SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.first_valid, r.last_valid, r.fetched_at,
       r.kind, r.step, r.provider_segment_end
FROM forecast_run r
JOIN series_eff e ON e.series_id = r.series_id
JOIN source fs ON fs.id = r.source_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
  AND fs.audience IN ('public') AND fs.lic_display;

CREATE VIEW pub_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public') AND fs.lic_display
    AND r.id = v.run_id);

CREATE VIEW pub_warning WITH (security_barrier = true) AS
SELECT w.id, w.source_id, w.area_key, w.name, w.geometry_geojson, w.level_norm, w.level_raw, w.label_raw, w.valid,
       w.issued_at
FROM warning_area w
JOIN source ws ON ws.id = w.source_id
WHERE ws.audience IN ('public') AND ws.lic_display;

CREATE VIEW pub_attribution WITH (security_barrier = true) AS
SELECT a.source_id, a.ord, a.lang, a.text, a.url, a.needs_date, a.date_kind, a.logo_allowed, a.required
FROM attribution a
JOIN source s ON s.id = a.source_id
WHERE s.audience IN ('public') AND s.lic_display;

CREATE VIEW pub_source_health WITH (security_barrier = true) AS
SELECT h.source_id, h.last_fetch_ok, h.last_new_data, h.newest_ts, h.consecutive_failures, h.quarantine_count,
       EXTRACT(EPOCH FROM h.lag_p95)::double precision AS lag_p95_s, h.status, h.detail, h.updated_at
FROM source_health h
JOIN source s ON s.id = h.source_id
WHERE s.audience IN ('public');

CREATE VIEW pub_twin_check WITH (security_barrier = true) AS
SELECT t.twin_id, t.window_end, t.n_aligned, t.median_delta, t.max_delta, t.lag_min, t.ok
FROM twin_check t
JOIN twin w ON w.id = t.twin_id
JOIN series_eff a ON a.series_id = w.series_a
JOIN series_eff b ON b.series_id = w.series_b
WHERE a.audience IN ('public') AND a.lic_display
  AND b.audience IN ('public') AND b.lic_display;

CREATE VIEW pub_ingest_batch WITH (security_barrier = true) AS
SELECT b.id, b.source_id, b.spec_id, b.fetched_at, b.parse_status, b.n_rows, b.n_new, b.n_changed, b.error,
       b.loaded_at
FROM ingest_batch b
JOIN source s ON s.id = b.source_id
WHERE s.audience IN ('public');

CREATE VIEW pub_api_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api;

CREATE VIEW pub_api_obs WITH (security_barrier = true) AS
SELECT o.series_id, o.ts, o.value, o.qc
FROM obs o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window);

CREATE VIEW pub_api_obs_1h WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1h o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW pub_api_obs_1d WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1d o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW pub_api_forecast_run WITH (security_barrier = true) AS
SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.first_valid, r.last_valid, r.fetched_at,
       r.kind, r.step, r.provider_segment_end
FROM forecast_run r
JOIN series_eff e ON e.series_id = r.series_id
JOIN source fs ON fs.id = r.source_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND fs.audience IN ('public') AND fs.lic_display AND fs.lic_api;

CREATE VIEW pub_api_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api
    AND fs.audience IN ('public') AND fs.lic_display AND fs.lic_api
    AND r.id = v.run_id);

CREATE VIEW own_station WITH (security_barrier = true) AS
SELECT st.id, st.name, st.water_name, st.country, st.lon, st.lat, st.river_id, st.reach_id, st.km_official,
       st.km_system, st.km_to_nl_entry, st.nl_entry_node, st.flags, st.tier
FROM station st
WHERE EXISTS (SELECT 1 FROM series_eff e WHERE e.station_id = st.id AND e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display);

CREATE VIEW own_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display;

CREATE VIEW own_obs WITH (security_barrier = true) AS
SELECT o.series_id, o.ts, o.value, o.qc
FROM obs o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window);

CREATE VIEW own_obs_latest WITH (security_barrier = true) AS
SELECT o.series_id, o.ts, o.value, o.qc
FROM obs_latest o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window);

CREATE VIEW own_obs_1h WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1h o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW own_obs_1d WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1d o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW own_reference WITH (security_barrier = true) AS
SELECT r.series_id, r.source_id, r.kind, r.value, r.unit, r.semantics, r.percentile_convention, r.period,
       r.season_from_md, r.season_to_md, r.priority, r.basis_label, r.valid
FROM reference_value r
JOIN series_eff e ON e.series_id = r.series_id
JOIN source rs ON rs.id = r.source_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
  AND rs.audience IN ('public', 'owner') AND rs.lic_display;

CREATE VIEW own_class WITH (security_barrier = true) AS
SELECT c.subject_type, c.subject_id, c.ts, c.source_id, c.provider_code, c.provider_label, c.level_norm
FROM class_obs c
JOIN source cs ON cs.id = c.source_id
WHERE cs.audience IN ('public', 'owner') AND cs.lic_display
  AND (c.subject_type = 'area'
       OR EXISTS (SELECT 1 FROM series_eff e WHERE e.station_id = c.subject_id AND e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display));

CREATE VIEW own_forecast_run WITH (security_barrier = true) AS
SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.first_valid, r.last_valid, r.fetched_at,
       r.kind, r.step, r.provider_segment_end
FROM forecast_run r
JOIN series_eff e ON e.series_id = r.series_id
JOIN source fs ON fs.id = r.source_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
  AND fs.audience IN ('public', 'owner') AND fs.lic_display;

CREATE VIEW own_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public', 'owner') AND fs.lic_display
    AND r.id = v.run_id);

CREATE VIEW own_warning WITH (security_barrier = true) AS
SELECT w.id, w.source_id, w.area_key, w.name, w.geometry_geojson, w.level_norm, w.level_raw, w.label_raw, w.valid,
       w.issued_at
FROM warning_area w
JOIN source ws ON ws.id = w.source_id
WHERE ws.audience IN ('public', 'owner') AND ws.lic_display;

CREATE VIEW own_attribution WITH (security_barrier = true) AS
SELECT a.source_id, a.ord, a.lang, a.text, a.url, a.needs_date, a.date_kind, a.logo_allowed, a.required
FROM attribution a
JOIN source s ON s.id = a.source_id
WHERE s.audience IN ('public', 'owner') AND s.lic_display;

CREATE VIEW own_source_health WITH (security_barrier = true) AS
SELECT h.source_id, h.last_fetch_ok, h.last_new_data, h.newest_ts, h.consecutive_failures, h.quarantine_count,
       EXTRACT(EPOCH FROM h.lag_p95)::double precision AS lag_p95_s, h.status, h.detail, h.updated_at
FROM source_health h
JOIN source s ON s.id = h.source_id
WHERE s.audience IN ('public', 'owner');

CREATE VIEW own_twin_check WITH (security_barrier = true) AS
SELECT t.twin_id, t.window_end, t.n_aligned, t.median_delta, t.max_delta, t.lag_min, t.ok
FROM twin_check t
JOIN twin w ON w.id = t.twin_id
JOIN series_eff a ON a.series_id = w.series_a
JOIN series_eff b ON b.series_id = w.series_b
WHERE a.audience IN ('public', 'owner') AND a.lic_display
  AND b.audience IN ('public', 'owner') AND b.lic_display;

CREATE VIEW own_ingest_batch WITH (security_barrier = true) AS
SELECT b.id, b.source_id, b.spec_id, b.fetched_at, b.parse_status, b.n_rows, b.n_new, b.n_changed, b.error,
       b.loaded_at
FROM ingest_batch b
JOIN source s ON s.id = b.source_id
WHERE s.audience IN ('public', 'owner');

CREATE VIEW own_api_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api;

CREATE VIEW own_api_obs WITH (security_barrier = true) AS
SELECT o.series_id, o.ts, o.value, o.qc
FROM obs o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window);

CREATE VIEW own_api_obs_1h WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1h o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW own_api_obs_1d WITH (security_barrier = true) AS
SELECT o.series_id, o.bucket, o.vmin, o.vmax, o.vavg, o.vlast, o.n, o.qc_or
FROM obs_1d o
JOIN series_eff e ON e.series_id = o.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND (e.lic_history_export OR o.bucket >= statement_timestamp() - e.history_window);

CREATE VIEW own_api_forecast_run WITH (security_barrier = true) AS
SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.first_valid, r.last_valid, r.fetched_at,
       r.kind, r.step, r.provider_segment_end
FROM forecast_run r
JOIN series_eff e ON e.series_id = r.series_id
JOIN source fs ON fs.id = r.source_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api
  AND fs.audience IN ('public', 'owner') AND fs.lic_display AND fs.lic_api;

CREATE VIEW own_api_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api
    AND fs.audience IN ('public', 'owner') AND fs.lic_display AND fs.lic_api
    AND r.id = v.run_id);

CREATE VIEW pub_owner_health WITH (security_barrier = true) AS
SELECT (count(*) FILTER (WHERE h.status = 'ok'))::int AS healthy, count(*)::int AS total
FROM source s
LEFT JOIN source_health h ON h.source_id = s.id
WHERE s.audience = 'owner' AND s.capture_enabled AND NOT s.canary;

CREATE VIEW own_private_basis WITH (security_barrier = true) AS
SELECT s.id AS source_id, s.private_basis
FROM source s
WHERE s.audience = 'owner';

CREATE VIEW pub_loader WITH (security_barrier = true) AS
SELECT (m.value ->> 'computed_at')::timestamptz AS computed_at,
       (m.value ->> 'backlog_files')::int AS backlog_files,
       (m.value ->> 'backlog_bytes')::bigint AS backlog_bytes,
       (m.value ->> 'backlog_age_s')::double precision AS backlog_age_s,
       (m.value ->> 'bad_manifest_lines')::int AS bad_manifest_lines
FROM app_meta m
WHERE m.key = 'loader';

CREATE FUNCTION pub_obs_at(p_t timestamptz)
RETURNS TABLE (series_id int, ts timestamptz, value real, qc int2)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
SET TimeZone = 'UTC'
ROWS 3000
AS $$
  SELECT e.series_id, o.ts, o.value, o.qc
  FROM public.series_eff e
  JOIN public.series s ON s.id = e.series_id
  CROSS JOIN LATERAL (
    SELECT o.ts, o.value, o.qc
    FROM public.obs o
    WHERE o.series_id = e.series_id AND o.ts <= p_t AND o.ts > p_t - s.staleness_limit
      AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window)
    ORDER BY o.ts DESC
    LIMIT 1) o
  WHERE s.active AND e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
$$;
REVOKE ALL ON FUNCTION pub_obs_at(timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION pub_obs_at(timestamptz) TO rws_api, rws_publish;

CREATE FUNCTION own_obs_at(p_t timestamptz)
RETURNS TABLE (series_id int, ts timestamptz, value real, qc int2)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
SET TimeZone = 'UTC'
ROWS 3000
AS $$
  SELECT e.series_id, o.ts, o.value, o.qc
  FROM public.series_eff e
  JOIN public.series s ON s.id = e.series_id
  CROSS JOIN LATERAL (
    SELECT o.ts, o.value, o.qc
    FROM public.obs o
    WHERE o.series_id = e.series_id AND o.ts <= p_t AND o.ts > p_t - s.staleness_limit
      AND (e.lic_history_export OR o.ts >= statement_timestamp() - e.history_window)
    ORDER BY o.ts DESC
    LIMIT 1) o
  WHERE s.active AND e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
$$;
REVOKE ALL ON FUNCTION own_obs_at(timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION own_obs_at(timestamptz) TO rws_owner_api;

GRANT SELECT ON pub_station,
  pub_series,
  pub_obs,
  pub_obs_latest,
  pub_obs_1h,
  pub_obs_1d,
  pub_reference,
  pub_class,
  pub_forecast_run,
  pub_forecast_value,
  pub_warning,
  pub_attribution,
  pub_source_health,
  pub_twin_check,
  pub_ingest_batch,
  pub_api_series,
  pub_api_obs,
  pub_api_obs_1h,
  pub_api_obs_1d,
  pub_api_forecast_run,
  pub_api_forecast_value,
  pub_owner_health,
  pub_loader
  TO rws_api, rws_publish;
GRANT SELECT ON own_station,
  own_series,
  own_obs,
  own_obs_latest,
  own_obs_1h,
  own_obs_1d,
  own_reference,
  own_class,
  own_forecast_run,
  own_forecast_value,
  own_warning,
  own_attribution,
  own_source_health,
  own_twin_check,
  own_ingest_batch,
  own_api_series,
  own_api_obs,
  own_api_obs_1h,
  own_api_obs_1d,
  own_api_forecast_run,
  own_api_forecast_value,
  own_private_basis
  TO rws_owner_api;

-- migrate:down
DROP FUNCTION own_obs_at(timestamptz);
DROP FUNCTION pub_obs_at(timestamptz);
DROP VIEW pub_loader;
DROP VIEW own_private_basis;
DROP VIEW pub_owner_health;
DROP VIEW own_api_forecast_value;
DROP VIEW own_api_forecast_run;
DROP VIEW own_api_obs_1d;
DROP VIEW own_api_obs_1h;
DROP VIEW own_api_obs;
DROP VIEW own_api_series;
DROP VIEW own_ingest_batch;
DROP VIEW own_twin_check;
DROP VIEW own_source_health;
DROP VIEW own_attribution;
DROP VIEW own_warning;
DROP VIEW own_forecast_value;
DROP VIEW own_forecast_run;
DROP VIEW own_class;
DROP VIEW own_reference;
DROP VIEW own_obs_1d;
DROP VIEW own_obs_1h;
DROP VIEW own_obs_latest;
DROP VIEW own_obs;
DROP VIEW own_series;
DROP VIEW own_station;
DROP VIEW pub_api_forecast_value;
DROP VIEW pub_api_forecast_run;
DROP VIEW pub_api_obs_1d;
DROP VIEW pub_api_obs_1h;
DROP VIEW pub_api_obs;
DROP VIEW pub_api_series;
DROP VIEW pub_ingest_batch;
DROP VIEW pub_twin_check;
DROP VIEW pub_source_health;
DROP VIEW pub_attribution;
DROP VIEW pub_warning;
DROP VIEW pub_forecast_value;
DROP VIEW pub_forecast_run;
DROP VIEW pub_class;
DROP VIEW pub_reference;
DROP VIEW pub_obs_1d;
DROP VIEW pub_obs_1h;
DROP VIEW pub_obs_latest;
DROP VIEW pub_obs;
DROP VIEW pub_series;
DROP VIEW pub_station;
DROP VIEW series_eff;
