-- GENERATED by scripts/gen-views.ts from apps/server/src/db/audience.ts. Do not edit:
-- change the generator and run it again (CI fails on a difference).
--
-- A view pair added after the first views migration (which never changes once
-- applied), with the same rules: security_barrier, granted to its family only.

-- migrate:up
CREATE VIEW pub_gauge_zero WITH (security_barrier = true) AS
SELECT z.series_id, z.value_m, z.datum, z.valid
FROM gauge_zero z
JOIN series_eff e ON e.series_id = z.series_id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display;

CREATE VIEW own_gauge_zero WITH (security_barrier = true) AS
SELECT z.series_id, z.value_m, z.datum, z.valid
FROM gauge_zero z
JOIN series_eff e ON e.series_id = z.series_id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display;

GRANT SELECT ON pub_gauge_zero TO rws_api, rws_publish;
GRANT SELECT ON own_gauge_zero TO rws_owner_api;

-- migrate:down
DROP VIEW own_gauge_zero;
DROP VIEW pub_gauge_zero;
