-- GENERATED by scripts/gen-views.ts from apps/server/src/db/audience.ts. Do not edit:
-- change the generator and run it again (CI fails on a difference).
--
-- P8a: the forecast value views gain p30 and p70 (appended; the views keep their
-- grants), and A§8 Q2 becomes one "latest run as of T" function per family,
-- SECURITY DEFINER like the observation functions, EXECUTE for the family only.

-- migrate:up
CREATE OR REPLACE VIEW pub_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags,
       v.p30, v.p70
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public') AND fs.lic_display
    AND r.id = v.run_id);

CREATE OR REPLACE VIEW pub_api_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags,
       v.p30, v.p70
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api
    AND fs.audience IN ('public') AND fs.lic_display AND fs.lic_api
    AND r.id = v.run_id);

CREATE OR REPLACE VIEW own_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags,
       v.p30, v.p70
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public', 'owner') AND fs.lic_display
    AND r.id = v.run_id);

CREATE OR REPLACE VIEW own_api_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags,
       v.p30, v.p70
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api
    AND fs.audience IN ('public', 'owner') AND fs.lic_display AND fs.lic_api
    AND r.id = v.run_id);

CREATE FUNCTION pub_forecast_at(p_asof timestamptz, p_t timestamptz)
RETURNS TABLE (run_id bigint, series_id int, source_id text, issued_at timestamptz, issued_inferred boolean,
               fetched_at timestamptz, first_valid timestamptz, last_valid timestamptz, kind text, step interval,
               provider_segment_end timestamptz, valid_ts timestamptz, value real, p05 real, p10 real, p25 real,
               p30 real, p50 real, p70 real, p75 real, p90 real, p95 real, vmin real, vmax real, flags int2)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
SET TimeZone = 'UTC'
ROWS 300
AS $$
  WITH RECURSIVE pairs AS (
    (SELECT r.series_id, r.source_id FROM public.forecast_run r ORDER BY r.series_id, r.source_id LIMIT 1)
    UNION ALL
    SELECT n.series_id, n.source_id
    FROM pairs p
    CROSS JOIN LATERAL (
      SELECT r.series_id, r.source_id
      FROM public.forecast_run r
      WHERE (r.series_id, r.source_id) > (p.series_id, p.source_id)
      ORDER BY r.series_id, r.source_id
      LIMIT 1) n
  )
  SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.fetched_at, r.first_valid, r.last_valid,
         r.kind, r.step, r.provider_segment_end, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p30, v.p50, v.p70, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
  FROM pairs p
  JOIN public.series_eff e ON e.series_id = p.series_id
  JOIN public.source fs ON fs.id = p.source_id
  CROSS JOIN LATERAL (
    SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.fetched_at, r.first_valid,
           r.last_valid, r.kind, r.step, r.provider_segment_end
    FROM public.forecast_run r
    WHERE r.series_id = p.series_id AND r.source_id = p.source_id
      AND COALESCE(r.issued_at, r.fetched_at) <= p_asof AND r.fetched_at <= p_asof
    ORDER BY COALESCE(r.issued_at, r.fetched_at) DESC, r.fetched_at DESC, r.id DESC
    LIMIT 1) r
  CROSS JOIN LATERAL (
    SELECT v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p30, v.p50, v.p70, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
    FROM public.forecast_value v
    WHERE v.run_id = r.id AND v.valid_ts >= r.first_valid AND v.valid_ts <= p_t
    ORDER BY v.valid_ts DESC
    LIMIT 1) v
  WHERE p_t >= p_asof AND r.first_valid <= p_t AND r.last_valid >= p_t
    AND e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public') AND fs.lic_display
$$;
REVOKE ALL ON FUNCTION pub_forecast_at(timestamptz, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION pub_forecast_at(timestamptz, timestamptz) TO rws_api, rws_publish;

CREATE FUNCTION own_forecast_at(p_asof timestamptz, p_t timestamptz)
RETURNS TABLE (run_id bigint, series_id int, source_id text, issued_at timestamptz, issued_inferred boolean,
               fetched_at timestamptz, first_valid timestamptz, last_valid timestamptz, kind text, step interval,
               provider_segment_end timestamptz, valid_ts timestamptz, value real, p05 real, p10 real, p25 real,
               p30 real, p50 real, p70 real, p75 real, p90 real, p95 real, vmin real, vmax real, flags int2)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
SET TimeZone = 'UTC'
ROWS 300
AS $$
  WITH RECURSIVE pairs AS (
    (SELECT r.series_id, r.source_id FROM public.forecast_run r ORDER BY r.series_id, r.source_id LIMIT 1)
    UNION ALL
    SELECT n.series_id, n.source_id
    FROM pairs p
    CROSS JOIN LATERAL (
      SELECT r.series_id, r.source_id
      FROM public.forecast_run r
      WHERE (r.series_id, r.source_id) > (p.series_id, p.source_id)
      ORDER BY r.series_id, r.source_id
      LIMIT 1) n
  )
  SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.fetched_at, r.first_valid, r.last_valid,
         r.kind, r.step, r.provider_segment_end, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p30, v.p50, v.p70, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
  FROM pairs p
  JOIN public.series_eff e ON e.series_id = p.series_id
  JOIN public.source fs ON fs.id = p.source_id
  CROSS JOIN LATERAL (
    SELECT r.id, r.series_id, r.source_id, r.issued_at, r.issued_inferred, r.fetched_at, r.first_valid,
           r.last_valid, r.kind, r.step, r.provider_segment_end
    FROM public.forecast_run r
    WHERE r.series_id = p.series_id AND r.source_id = p.source_id
      AND COALESCE(r.issued_at, r.fetched_at) <= p_asof AND r.fetched_at <= p_asof
    ORDER BY COALESCE(r.issued_at, r.fetched_at) DESC, r.fetched_at DESC, r.id DESC
    LIMIT 1) r
  CROSS JOIN LATERAL (
    SELECT v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p30, v.p50, v.p70, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
    FROM public.forecast_value v
    WHERE v.run_id = r.id AND v.valid_ts >= r.first_valid AND v.valid_ts <= p_t
    ORDER BY v.valid_ts DESC
    LIMIT 1) v
  WHERE p_t >= p_asof AND r.first_valid <= p_t AND r.last_valid >= p_t
    AND e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public', 'owner') AND fs.lic_display
$$;
REVOKE ALL ON FUNCTION own_forecast_at(timestamptz, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION own_forecast_at(timestamptz, timestamptz) TO rws_owner_api;

-- migrate:down
DROP FUNCTION own_forecast_at(timestamptz, timestamptz);
DROP FUNCTION pub_forecast_at(timestamptz, timestamptz);
DROP VIEW pub_forecast_value;
DROP VIEW pub_api_forecast_value;
DROP VIEW own_forecast_value;
DROP VIEW own_api_forecast_value;

CREATE VIEW pub_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public') AND fs.lic_display
    AND r.id = v.run_id);

GRANT SELECT ON pub_forecast_value TO rws_api, rws_publish;

CREATE VIEW pub_api_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api
    AND fs.audience IN ('public') AND fs.lic_display AND fs.lic_api
    AND r.id = v.run_id);

GRANT SELECT ON pub_api_forecast_value TO rws_api, rws_publish;

CREATE VIEW own_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display
    AND fs.audience IN ('public', 'owner') AND fs.lic_display
    AND r.id = v.run_id);

GRANT SELECT ON own_forecast_value TO rws_owner_api;

CREATE VIEW own_api_forecast_value WITH (security_barrier = true) AS
SELECT v.run_id, v.valid_ts, v.value, v.p05, v.p10, v.p25, v.p50, v.p75, v.p90, v.p95, v.vmin, v.vmax, v.flags
FROM forecast_value v
WHERE EXISTS (SELECT 1
  FROM forecast_run r
  JOIN series_eff e ON e.series_id = r.series_id
  JOIN source fs ON fs.id = r.source_id
  WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api
    AND fs.audience IN ('public', 'owner') AND fs.lic_display AND fs.lic_api
    AND r.id = v.run_id);

GRANT SELECT ON own_api_forecast_value TO rws_owner_api;
