-- migrate:up

-- Provenance and operations (A§6).

-- One row per archived payload that reached an adapter or was set aside. The
-- archive key is the natural key: a replay updates the row, it never adds one.
CREATE TABLE ingest_batch (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id       text NOT NULL REFERENCES source,
  spec_id         text NOT NULL CHECK (spec_id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  archive_key     text NOT NULL UNIQUE,
  sha256          text CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  fetched_at      timestamptz NOT NULL,
  http_status     int2,
  bytes           bigint,
  adapter_version int NOT NULL,
  parse_status    text NOT NULL CHECK (parse_status IN ('ok', 'quarantined', 'skipped')),
  n_rows          int NOT NULL DEFAULT 0,
  n_new           int NOT NULL DEFAULT 0,
  n_changed       int NOT NULL DEFAULT 0,
  -- One of our own fixed codes, optionally with a schema path: never provider
  -- text, a URL, a secret or a database message (invariant 6).
  error           text CHECK (error ~ '^[a-z0-9_]{1,40}( at [A-Za-z0-9_.?\[\]-]{1,120})?$'),
  loaded_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ingest_batch_source_status ON ingest_batch (source_id, parse_status);
CREATE INDEX ingest_batch_fetched ON ingest_batch (fetched_at);

-- How far the loader has read each daily manifest file (bytes).
CREATE TABLE load_cursor (
  manifest_file text PRIMARY KEY CHECK (manifest_file ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}\.jsonl$'),
  byte_offset   bigint NOT NULL CHECK (byte_offset >= 0),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Per-source health, precomputed by the loader; the API only reads it.
CREATE TABLE source_health (
  source_id            text PRIMARY KEY REFERENCES source,
  last_fetch_ok        timestamptz,
  last_new_data        timestamptz,
  newest_ts            timestamptz,
  consecutive_failures int NOT NULL DEFAULT 0,
  circuit_state        text,
  quarantine_count     int NOT NULL DEFAULT 0,
  lag_p95              interval,
  status               text NOT NULL DEFAULT 'unknown' CHECK (status IN ('ok', 'degraded', 'down', 'unknown')),
  -- {tier1: {total, fresh, provider_stale}, missing_buckets_24h, partitions: {name: {md5, rows}}, …}:
  -- counts and checksums only, over the series that share the source's audience.
  detail               jsonb NOT NULL DEFAULT '{}',
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE twin_check (
  twin_id      text NOT NULL REFERENCES twin,
  window_end   timestamptz NOT NULL,
  n_aligned    int NOT NULL,
  median_delta real,
  max_delta    real,
  lag_min      real,
  ok           boolean NOT NULL,
  PRIMARY KEY (twin_id, window_end)
);

-- data_epoch, display_start, day_versions, loader state.
CREATE TABLE app_meta (
  key        text PRIMARY KEY,
  value      jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- migrate:down

DROP TABLE app_meta;
DROP TABLE twin_check;
DROP TABLE source_health;
DROP TABLE load_cursor;
DROP TABLE ingest_batch;
