-- GENERATED by scripts/gen-views.ts from apps/server/src/db/audience.ts. Do not edit:
-- change the generator and run it again (CI fails on a difference).
--
-- P9a: the series views gain the effective api and history_export channels and the history window (appended; the
-- views keep their grants), and the publishers' three view pairs: the dirty log, the day versions and the sources,
-- security_barrier and granted to their family only.

-- migrate:up
CREATE OR REPLACE VIEW pub_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience, e.lic_api, e.lic_history_export, e.history_window
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display;

CREATE OR REPLACE VIEW pub_api_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience, e.lic_api, e.lic_history_export, e.history_window
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api;

CREATE OR REPLACE VIEW own_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience, e.lic_api, e.lic_history_export, e.history_window
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display;

CREATE OR REPLACE VIEW own_api_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience, e.lic_api, e.lic_history_export, e.history_window
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api;

CREATE VIEW pub_dirty WITH (security_barrier = true) AS
SELECT d.id, d.kind, d.from_ts, d.to_ts, d.stations, d.created_at
FROM publish_dirty d
WHERE d.family = 'public';

CREATE VIEW pub_day_version WITH (security_barrier = true) AS
SELECT j.key::date AS day, (j.value ->> 'v')::int AS version, j.value ->> 'reason' AS reason,
       (j.value ->> 'at')::timestamptz AS at
FROM app_meta m
CROSS JOIN LATERAL jsonb_each(m.value) j
WHERE m.key = 'day_versions:public';

CREATE VIEW pub_source WITH (security_barrier = true) AS
SELECT s.id, s.name, pr.name AS provider, s.licence_kind, pr.terms_url, s.audience
FROM source s
JOIN provider pr ON pr.id = s.provider_id
WHERE s.audience IN ('public') AND s.lic_display;

CREATE VIEW own_dirty WITH (security_barrier = true) AS
SELECT d.id, d.kind, d.from_ts, d.to_ts, d.stations, d.created_at
FROM publish_dirty d
WHERE d.family = 'owner';

CREATE VIEW own_day_version WITH (security_barrier = true) AS
SELECT j.key::date AS day, (j.value ->> 'v')::int AS version, j.value ->> 'reason' AS reason,
       (j.value ->> 'at')::timestamptz AS at
FROM app_meta m
CROSS JOIN LATERAL jsonb_each(m.value) j
WHERE m.key = 'day_versions:owner';

CREATE VIEW own_source WITH (security_barrier = true) AS
SELECT s.id, s.name, pr.name AS provider, s.licence_kind, pr.terms_url, s.audience
FROM source s
JOIN provider pr ON pr.id = s.provider_id
WHERE s.audience IN ('public', 'owner') AND s.lic_display;

GRANT SELECT ON pub_dirty TO rws_api, rws_publish;
GRANT SELECT ON pub_day_version TO rws_api, rws_publish;
GRANT SELECT ON pub_source TO rws_api, rws_publish;
GRANT SELECT ON own_dirty TO rws_owner_api;
GRANT SELECT ON own_day_version TO rws_owner_api;
GRANT SELECT ON own_source TO rws_owner_api;

-- migrate:down
DROP VIEW own_source;
DROP VIEW own_day_version;
DROP VIEW own_dirty;
DROP VIEW pub_source;
DROP VIEW pub_day_version;
DROP VIEW pub_dirty;
DROP VIEW pub_series;
DROP VIEW pub_api_series;
DROP VIEW own_series;
DROP VIEW own_api_series;

CREATE VIEW pub_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display;

GRANT SELECT ON pub_series TO rws_api, rws_publish;

CREATE VIEW pub_api_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public') AND e.role = 'primary' AND e.lic_display AND e.lic_api;

GRANT SELECT ON pub_api_series TO rws_api, rws_publish;

CREATE VIEW own_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display;

GRANT SELECT ON own_series TO rws_owner_api;

CREATE VIEW own_api_series WITH (security_barrier = true) AS
SELECT s.id, s.station_id, s.source_id, s.quantity, s.value_kind, s.native_unit, s.to_canonical, s.datum,
       s.expected_step, s.staleness_limit, s.active, e.audience
FROM series s
JOIN series_eff e ON e.series_id = s.id
WHERE e.audience IN ('public', 'owner') AND e.role = 'primary' AND e.lic_display AND e.lic_api;

GRANT SELECT ON own_api_series TO rws_owner_api;
