import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { isExpression, type StyleSpecification, validateStyleMin } from '@maplibre/maplibre-gl-style-spec';
import { describe, expect, it } from 'vitest';
import { parseAllDocuments } from 'yaml';
import {
  ATTRIBUTION,
  buildStyle,
  ROOT,
  readBasemap,
  STYLES_DIR,
  styleFile,
  styleText,
} from '../tools/geo/basemap/build-style.ts';

// The basemap styles (P3, ADR-0016) are generated by tools/geo/basemap/build-style.ts from the pinned
// @protomaps/basemaps layer set. Offline: the committed styles are the generator's output, valid
// MapLibre styles, name no third-party host, use only what the tiles and the pinned glyph and sprite
// files hold, and the committed assets are exactly what their SHA256SUMS lists.

const b = readBasemap();
const ASSETS = '/assets/map/028c18f/';
const assetsDir = join(ROOT, 'apps/web/public', ASSETS);
const regional = b.style.regional_minzoom;
const sha256 = (data: Buffer | string) => createHash('sha256').update(data).digest('hex');
const read = (lang: string) => JSON.parse(readFileSync(styleFile(lang), 'utf8')) as StyleSpecification;

/** Every string value of a JSON document. */
function strings(value: unknown, out: string[] = []): string[] {
  if (typeof value === 'string') out.push(value);
  else if (Array.isArray(value)) for (const x of value) strings(x, out);
  else if (value !== null && typeof value === 'object') for (const x of Object.values(value)) strings(x, out);
  return out;
}

/** The font stacks of one `text-font` value: a plain array, or the literal arrays inside an expression. */
function stacksOf(value: unknown): string[][] {
  if (!Array.isArray(value)) return [];
  if (!isExpression(value)) return [value as string[]];
  if (value[0] === 'literal') return [value[1] as string[]];
  return value.slice(1).flatMap(stacksOf);
}

/** Every `text-font` of a layer list, in layouts and in the sections of `format` expressions. */
function textFonts(node: unknown, out: string[][] = []): string[][] {
  if (Array.isArray(node)) for (const x of node) textFonts(x, out);
  else if (node !== null && typeof node === 'object') {
    for (const [key, value] of Object.entries(node)) {
      if (key === 'text-font') out.push(...stacksOf(value));
      textFonts(value, out);
    }
  }
  return out;
}

/** The files under the assets directory, by path relative to it; a link or anything else is a failure. */
function assetFiles(): string[] {
  const out: string[] = [];
  for (const e of readdirSync(assetsDir, { recursive: true, withFileTypes: true })) {
    if (e.isDirectory()) continue;
    if (!e.isFile()) throw new Error(`${e.name}: not a regular file`);
    out.push(relative(assetsDir, join(e.parentPath, e.name)));
  }
  return out;
}

describe.each(b.style.langs)('apps/web/src/features/map/styles/style-%s.json', (lang) => {
  const style = read(lang);

  it('is exactly what the generator writes', () => {
    expect(sha256(readFileSync(styleFile(lang), 'utf8'))).toBe(sha256(styleText(buildStyle(b, lang).style)));
  });

  it('labels in its language (name:<lang>, with the English name as the fallback)', () => {
    expect(readFileSync(styleFile(lang), 'utf8')).toContain(`"name:${lang}"`);
  });

  it('is a valid MapLibre style (maplibre-gl-style-spec validateStyleMin)', () => {
    expect(validateStyleMin(style).map((e) => e.message)).toEqual([]);
  });

  it('names no third-party host: only the two PMTiles placeholders and the credit hold a URL', () => {
    expect(style.glyphs?.startsWith(ASSETS)).toBe(true);
    expect(typeof style.sprite === 'string' && style.sprite.startsWith(ASSETS)).toBe(true);
    expect(Object.keys(style.sources).sort()).toEqual(['basemap', 'planet']);
    for (const name of ['planet', 'basemap']) {
      expect(style.sources[name]).toEqual({ type: 'vector', url: `pmtiles://${name}`, attribution: ATTRIBUTION });
    }
    const allowed = new Set([ATTRIBUTION, 'pmtiles://planet', 'pmtiles://basemap']);
    const urls = strings(style).filter((s) => s.includes('://') || s.startsWith('//'));
    expect(urls.filter((s) => !allowed.has(s))).toEqual([]);
    expect(ATTRIBUTION.match(/https?:\/\/[^"'\s<>]+/g)).toEqual(['https://www.openstreetmap.org/copyright']);
  });

  it('uses only source layers that the tiles have (lobith-z14.metadata.json vector_layers)', () => {
    const meta = JSON.parse(readFileSync(join(ROOT, 'tools/geo/fixtures/lobith-z14.metadata.json'), 'utf8')) as {
      vector_layers: { id: string }[];
    };
    const have = new Set(meta.vector_layers.map((l) => l.id));
    expect(have.size).toBeGreaterThan(0);
    const used = new Set(style.layers.flatMap((l) => ('source-layer' in l ? [l['source-layer']] : [])));
    expect(used.size).toBeGreaterThan(0);
    expect([...used].filter((id) => !have.has(id as string))).toEqual([]);
  });

  it('uses only font stacks and sprites that are served, and every label has a font', () => {
    const used = new Set(textFonts(style.layers).map((stack) => stack.join(',')));
    expect(used.size).toBeGreaterThan(0);
    for (const stack of used) expect(existsSync(join(assetsDir, 'fonts', stack)), stack).toBe(true);
    // Without a text-font MapLibre asks for its default stack, which is not served.
    const unfonted = style.layers.filter(
      (l) => l.type === 'symbol' && l.layout?.['text-field'] !== undefined && l.layout?.['text-font'] === undefined,
    );
    expect(unfonted.map((l) => l.id)).toEqual([]);
    // The registry lists no font the style does not use, and no font is used that it does not list.
    expect([...used].sort()).toEqual([...b.assets.fonts].sort());

    const sprite = (suffix: string) => join(assetsDir, 'sprites/v4', `${b.style.flavour}${suffix}`);
    for (const suffix of ['.json', '.png', '@2x.json', '@2x.png'])
      expect(existsSync(sprite(suffix)), suffix).toBe(true);
    // The plain icon names of the style (the shield names are built with concat from the sprite's names).
    const icons = JSON.parse(readFileSync(sprite('.json'), 'utf8')) as Record<string, unknown>;
    for (const name of ['arrow', 'capital', 'townspot']) expect(icons, name).toHaveProperty(name);
  });

  it('has one background, unique ids, and the zoom split at regional_minzoom', () => {
    const ids = style.layers.map((l) => l.id);
    expect(new Set(ids).size).toBe(ids.length);
    const backgrounds = style.layers.filter((l) => l.type === 'background');
    expect(backgrounds.map((l) => l.id)).toEqual(['planet:background']);
    expect(style.layers[0]?.id).toBe('planet:background');
    for (const l of style.layers) {
      expect((l.minzoom ?? 0) < (l.maxzoom ?? 24), `${l.id}: minzoom below maxzoom`).toBe(true);
      if (l.type === 'background') continue;
      expect(l.source, l.id).toBe(l.id.split(':')[0]);
    }
    const planetSymbols = style.layers.filter((l) => l.id.startsWith('planet:') && l.type === 'symbol');
    expect(planetSymbols.length).toBeGreaterThan(0);
    for (const l of planetSymbols) expect(l.maxzoom, l.id).toBeLessThanOrEqual(regional);
    const regionalLayers = style.layers.filter((l) => l.id.startsWith('basemap:'));
    expect(regionalLayers.length).toBeGreaterThan(0);
    for (const l of regionalLayers) expect(l.minzoom ?? 0, l.id).toBeGreaterThanOrEqual(regional);
  });

  it('drops only planet symbol layers that the zoom split leaves without a zoom range', () => {
    // A new @protomaps/basemaps layer set changes this list: review it, then update it.
    expect(buildStyle(b, lang).dropped).toEqual([
      'planet:address_label',
      'planet:water_waterway_label',
      'planet:roads_oneway',
      'planet:roads_labels_minor',
      'planet:roads_labels_major',
    ]);
  });
});

describe('the style files and the lockfile', () => {
  it('there is one style file per language and nothing else', () => {
    expect(readdirSync(STYLES_DIR).sort()).toEqual(b.style.langs.map((l) => `style-${l}.json`).sort());
  });

  it('maplibre-gl resolves the same style-spec as the root devDependency that validates these styles', () => {
    const root = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
      devDependencies: Record<string, string>;
    };
    const web = JSON.parse(readFileSync(join(ROOT, 'apps/web/package.json'), 'utf8')) as {
      dependencies: Record<string, string>;
    };
    const pinned = root.devDependencies['@maplibre/maplibre-gl-style-spec'];
    const maplibre = web.dependencies['maplibre-gl'];
    expect(pinned).toMatch(/^\d+\.\d+\.\d+$/);
    expect(maplibre).toMatch(/^\d+\.\d+\.\d+$/);
    type Lock = { snapshots?: Record<string, { dependencies?: Record<string, string> }> };
    // A multi-document file: pnpm's own pin comes first and has snapshots of its own.
    const snapshots: NonNullable<Lock['snapshots']> = {};
    for (const doc of parseAllDocuments(readFileSync(join(ROOT, 'pnpm-lock.yaml'), 'utf8'))) {
      Object.assign(snapshots, (doc.toJSON() as Lock | null)?.snapshots);
    }
    expect(snapshots[`maplibre-gl@${maplibre}`]?.dependencies?.['@maplibre/maplibre-gl-style-spec']).toBe(pinned);
    // And there is no second copy: what the client parses the style with is what validated it.
    const copies = Object.keys(snapshots).filter((k) => k.startsWith('@maplibre/maplibre-gl-style-spec@'));
    expect(copies).toEqual([`@maplibre/maplibre-gl-style-spec@${pinned}`]);
  });
});

describe(`apps/web/public${ASSETS}`, () => {
  const sums = readFileSync(join(assetsDir, 'SHA256SUMS'));
  const listed = sums
    .toString('utf8')
    .split('\n')
    .filter((line) => line !== '')
    .map((line) => {
      const m = /^([0-9a-f]{64}) {2}(.+)$/.exec(line);
      if (m === null) throw new Error('SHA256SUMS: a malformed line');
      return { sha: m[1] as string, path: m[2] as string };
    });

  it('is the directory of the registry commit', () => {
    expect(b.assets.commit.startsWith('028c18f')).toBe(true);
    expect(sha256(sums)).toBe(b.assets.sums_sha256);
  });

  it('lists every file with its sha256, sorted by path, and lists nothing that is missing', () => {
    const paths = listed.map((l) => l.path);
    expect(new Set(paths).size).toBe(paths.length);
    const byBytes = (x: string, y: string) => Buffer.compare(Buffer.from(x), Buffer.from(y));
    expect(paths).toEqual([...paths].sort(byBytes));
    for (const p of paths) expect(p.startsWith('/') || p.split('/').includes('..'), p).toBe(false);
    expect(paths).toEqual(
      assetFiles()
        .filter((f) => f !== 'SHA256SUMS')
        .sort(byBytes),
    );
    const wrong = listed.filter((l) => sha256(readFileSync(join(assetsDir, l.path))) !== l.sha).map((l) => l.path);
    expect(wrong).toEqual([]);
  });

  it('holds the 256 glyph ranges of every font, the licences and the flavour sprites', () => {
    for (const font of b.assets.fonts) {
      const dir = join(assetsDir, 'fonts', font);
      expect(statSync(dir).isDirectory(), font).toBe(true);
      const files = readdirSync(dir).sort();
      expect(files, font).toHaveLength(256);
      expect(
        files.filter((f) => !/^\d+-\d+\.pbf$/.test(f)),
        font,
      ).toEqual([]);
    }
    const paths = new Set(listed.map((l) => l.path));
    for (const p of [b.assets.licences.fonts.file, 'LICENSES.md', `sprites/v4/${b.style.flavour}@2x.png`]) {
      expect(paths.has(p), p).toBe(true);
    }
  });
});
