import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { CROSSWALK, REFERENCE_ROLES } from '../packages/core/src/index.ts';
import { generate } from '../scripts/gen-classification.ts';
import { repoRoot } from './catalogue.ts';

const committed = readFileSync(`${repoRoot}docs/classification.md`);

/** The table lines of a section (without the header and separator). */
const section = (text: string, heading: string) => {
  const i = text.indexOf(`\n## ${heading}\n`);
  if (i < 0) throw new Error(`no section ${heading}`);
  const rest = text.slice(i + 1).split('\n');
  const end = rest.findIndex((l, k) => k > 0 && l.startsWith('## '));
  return rest
    .slice(0, end < 0 ? undefined : end)
    .filter((l) => l.startsWith('| '))
    .slice(2);
};

describe('docs/classification.md', () => {
  const text = generate();

  it('equals generate() byte for byte', () => {
    expect(committed.equals(Buffer.from(text))).toBe(true);
  });

  it('fails the comparison after a one-character edit', () => {
    expect(committed.equals(Buffer.from(text.replace('Classification', 'Classificatiom')))).toBe(false);
  });

  it('starts with the GENERATED marker', () => {
    expect(text.split('\n')[0]).toMatch(/^<!-- GENERATED by scripts\/gen-classification\.ts .*Do not edit/);
  });

  it('lists every crosswalk row once, in its table', () => {
    const gauge = CROSSWALK.filter((r) => r.group !== 'area');
    const area = CROSSWALK.filter((r) => r.group === 'area');
    const g = section(text, 'Gauge classes');
    const a = section(text, 'Area classes');
    expect(g).toHaveLength(gauge.length);
    expect(a).toHaveLength(area.length);
    for (const [lines, rows] of [
      [g, gauge],
      [a, area],
    ] as const) {
      rows.forEach((r, i) => {
        expect(lines[i]?.startsWith(`| ${r.source} | ${r.scale} | ${r.code} | ${r.level} | ${r.basis} |`)).toBe(true);
      });
    }
  });

  it('lists every reference kind once', () => {
    const lines = section(text, 'Reference kinds');
    expect(lines).toHaveLength(REFERENCE_ROLES.length);
    REFERENCE_ROLES.forEach((r, i) => {
      expect(lines[i]?.startsWith(`| ${r.source} | ${r.kind} |`)).toBe(true);
    });
  });

  it('marks every owner row "owner view only" and gated rows "gated (P13)"', () => {
    const all = [
      ...section(text, 'Gauge classes'),
      ...section(text, 'Area classes'),
      ...section(text, 'Reference kinds'),
    ];
    const rows = [
      ...CROSSWALK.filter((r) => r.group !== 'area'),
      ...CROSSWALK.filter((r) => r.group === 'area'),
      ...REFERENCE_ROLES,
    ];
    expect(all).toHaveLength(rows.length);
    rows.forEach((r, i) => {
      if (r.audience === 'owner') expect(all[i]).toContain('| owner view only |');
      if (r.gated) expect(all[i]).toContain('| gated (P13) |');
    });
  });

  it('holds no threshold or canary value', () => {
    expect(text).not.toMatch(/777777|123456\.789/);
    expect(text).not.toContain('private_basis');
  });
});
