import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { parse } from 'yaml';
import { LhpStationsFile } from '../packages/contracts/src/tables.ts';
import { generate, type Inputs, OUTPUT, readInputs } from '../scripts/gen-de6-stations.ts';

// registry/classes/de-6.yaml is generated (scripts/gen-de6-stations.ts) from the recorded LHP stations payload and
// the DE-1 and DE-7 registries: the committed file is exactly the generator's output, every duplicate group has one
// operating state, and the groups of catalogue §4.9 are as the rule says.

const committed = readFileSync(OUTPUT, 'utf8');
const inputs = readInputs();
const table = LhpStationsFile.parse(parse(committed));
const of = (station: string) => table.stations.filter((s) => s.station === station);
const summary = (station: string) => of(station).map((s) => `${s.lhp}${s.operator ? '*' : ''}`);

describe('registry/classes/de-6.yaml', () => {
  it('is exactly the generator output, with the generated-file header', () => {
    expect(committed).toBe(generate(inputs));
    expect(committed).toMatch(/^# DE-6 LHP station table/);
    expect(committed).toContain('GENERATED by scripts/gen-de6-stations.ts');
    expect(committed).toContain(inputs.file.sha256);
  });

  it('every station has exactly one operating state, and a single feature is its own operator', () => {
    const stations = new Set(table.stations.map((s) => s.station));
    for (const station of stations)
      expect([station, of(station).filter((s) => s.operator).length]).toEqual([station, 1]);
    for (const station of stations) {
      const features = of(station);
      if (features.length === 1) expect(features[0]?.operator).toBe(true);
    }
    expect(table.stations).toHaveLength(163);
    expect(stations.size).toBe(157);
  });

  it('every station is one of ours (a DE-1 or DE-7 primary public stage series), its state is the id prefix', () => {
    const ours = new Set(inputs.stations.map((s) => s.id));
    for (const s of table.stations) {
      expect([s.lhp, ours.has(s.station)]).toEqual([s.lhp, true]);
      expect(s.lhp.slice(0, 2)).toBe(s.state);
    }
  });

  it('the duplicate groups of catalogue §4.9: Worms, Mainz, Kaub and Perl by RP; Obernau by BY; Kalkofen-neu by RP', () => {
    expect(summary('de.wsv.23900200')).toEqual(['HE_23900200', 'RP_23900200*']);
    expect(summary('de.wsv.25100100')).toEqual(['HE_25100100', 'RP_25100100*']);
    expect(summary('de.wsv.25700100')).toEqual(['HE_25700100', 'RP_25700100*']);
    expect(summary('de.wsv.25800600')).toEqual(['HE_25800600', 'RP_25800600*']);
    // Perl: the PEGELONLINE number is 26100100, both states list 26100102.
    expect(summary('de.wsv.26100100')).toEqual(['RP_26100102*', 'SL_26100102']);
    expect(summary('de.wsv.24700302')).toEqual(['BY_24070006*', 'HE_24700302']);
    // Kleinheubach: only the BY feature lies within 500 m (HE_24700200 is 625 m away, RP_26700200 Detzem 678 m).
    expect(summary('de.wsv.24700200')).toEqual(['BY_24064003*']);
    expect(table.stations.find((s) => s.lhp === 'HE_24700200')).toBeUndefined();
    expect(table.stations.find((s) => s.lhp === 'RP_26700200')).toBeUndefined();
  });

  it('the generator fails on a duplicate group without an OPERATOR entry, and on a number two stations share', () => {
    const feature = (id: string, lon: number, lat: number) => {
      const f = structuredClone(inputs.features[0]);
      if (f === undefined) throw new Error('no feature');
      return { ...f, id, geometry: { ...f.geometry, coordinates: [lon, lat] as [number, number] } };
    };
    const station = inputs.stations.find((s) => s.provider_code === '2721390000100');
    if (station === undefined) throw new Error('no station');
    const second = feature('HE_2721390000100', station.lon, station.lat);
    const withSecond: Inputs = { ...inputs, features: [...inputs.features, second] };
    expect(() => generate(withSecond)).toThrow(/duplicate group without OPERATOR/);
    const twice: Inputs = { ...inputs, stations: [...inputs.stations, { ...station, id: 'de.lanuk.other' }] };
    expect(() => generate(twice)).toThrow(/is on two stations/);
    // A feature that moved away from its station is no longer ours: the table shrinks, it does not fail.
    const far = feature('NW_2721390000100', station.lon + 1, station.lat);
    const moved: Inputs = {
      ...inputs,
      features: inputs.features.map((f) => (f.id === 'NW_2721390000100' ? far : f)),
    };
    expect(generate(moved)).not.toContain('NW_2721390000100');
  });
});
