-- When the five-minute latest poll last probed this (location, quantity) pair
-- for a series it does not already know.
--
-- The poll fetches known series in bulk, narrowed to their exact metadata.
-- A pair with no live series cannot be narrowed, so those are probed a few per
-- cycle in round-robin order instead of all at once -- a cold system otherwise
-- opens with thousands of unfiltered calls at Rijkswaterstaat. This column is
-- what makes the rotation fair across restarts.
--
-- No index: location_quantities holds a few tens of thousands of rows and the
-- ordering runs once per poll, so a sort is cheaper than a second index to
-- maintain on every refresh.
ALTER TABLE location_quantities ADD COLUMN polled_at timestamptz;
