import type { Audience, LicenceKind } from './registry.ts';

/**
 * The approved baseline per source ID: its initial audience (catalogue §0.8,
 * ADR-0017, issue #15) and our classification of its §1b licence cell.
 * `validateRegistry` compares registry/sources.yaml against it: a different
 * audience needs a permission record (registry/permissions/<ID>.md) that grants
 * it, and a different licence kind is never accepted without changing this
 * reviewed table (CODEOWNERS covers packages/contracts/).
 */
export const BASELINE: Readonly<Record<string, { audience: Audience; licence_kind: LicenceKind | null }>> = {
  'NL-1': { audience: 'public', licence_kind: 'cc0' },
  'NL-2': { audience: 'public', licence_kind: 'cc0' },
  'NL-3': { audience: 'off', licence_kind: 'unlicensed' },
  'NL-4': { audience: 'public', licence_kind: 'cc0' },
  'NL-5': { audience: 'off', licence_kind: 'unlicensed' },
  'NL-6': { audience: 'off', licence_kind: null },
  'DE-1': { audience: 'public', licence_kind: 'dl-de-zero-2.0' },
  'DE-2': { audience: 'owner', licence_kind: 'bfg-terms' },
  'DE-3': { audience: 'owner', licence_kind: 'bfg-terms' },
  'DE-4': { audience: 'off', licence_kind: 'dl-de-zero-2.0' },
  'DE-5': { audience: 'off', licence_kind: 'dl-de-zero-2.0' },
  'DE-6': { audience: 'public', licence_kind: 'cc-by' },
  'DE-7': { audience: 'public', licence_kind: 'dl-de-zero-2.0' },
  'DE-8': { audience: 'public', licence_kind: 'dl-de-zero-2.0' },
  'DE-9': { audience: 'off', licence_kind: 'provider-terms' },
  'DE-10': { audience: 'off', licence_kind: 'provider-terms' },
  'DE-11': { audience: 'off', licence_kind: 'cc-by' },
  'DE-12': { audience: 'off', licence_kind: 'provider-terms' },
  'DE-13': { audience: 'off', licence_kind: 'provider-terms' },
  'DE-14': { audience: 'off', licence_kind: null },
  'DE-15': { audience: 'off', licence_kind: 'cc-by-sa-4.0' },
  'DE-16': { audience: 'off', licence_kind: 'unlicensed' },
  'DE-17': { audience: 'off', licence_kind: 'provider-terms' },
  'BE-1': { audience: 'off', licence_kind: 'provider-terms' },
  'BE-2': { audience: 'off', licence_kind: 'modellicentie-1.0' },
  'BE-3': { audience: 'owner', licence_kind: 'provider-terms' },
  'BE-4': { audience: 'off', licence_kind: 'cc-by' },
  'BE-5': { audience: 'off', licence_kind: null },
  'FR-1': { audience: 'public', licence_kind: 'etalab-2.0' },
  'FR-2': { audience: 'off', licence_kind: 'etalab-2.0' },
  'FR-3': { audience: 'public', licence_kind: 'etalab-2.0' },
  'FR-4': { audience: 'public', licence_kind: 'etalab-2.0' },
  'FR-5': { audience: 'public', licence_kind: 'etalab-2.0' },
  'FR-6': { audience: 'off', licence_kind: null },
  'LU-1': { audience: 'public', licence_kind: 'cc0' },
  'LU-2': { audience: 'owner', licence_kind: 'provider-terms' },
  'LU-3': { audience: 'owner', licence_kind: 'provider-terms' },
  'LU-4': { audience: 'owner', licence_kind: 'provider-terms' },
  'LU-5': { audience: 'public', licence_kind: 'cc-by' },
  'LU-6': { audience: 'public', licence_kind: 'cc0' },
  'LU-7': { audience: 'off', licence_kind: null },
  'CH-1': { audience: 'public', licence_kind: 'ch-open-use' },
  'CH-2': { audience: 'public', licence_kind: 'ch-open-use' },
  'CH-3': { audience: 'public', licence_kind: 'ch-open-use' },
  'CH-4': { audience: 'public', licence_kind: 'ch-open-use' },
  'CH-5': { audience: 'public', licence_kind: 'ch-open-use' },
  'CH-6': { audience: 'off', licence_kind: 'ch-open-use' },
  'CH-7': { audience: 'off', licence_kind: 'ch-open-use' },
  'CH-8': { audience: 'off', licence_kind: 'ch-open-use' },
  'CH-9': { audience: 'off', licence_kind: 'ch-open-use' },
  'CH-10': { audience: 'off', licence_kind: 'unlicensed' },
  'CH-11': { audience: 'off', licence_kind: null },
  'CANARY-OWNER': { audience: 'owner', licence_kind: null },
};
