import { z } from 'zod';
import { ReachFlags, ReachId, TravelRange } from './reaches.ts';

// Station placement on the river graph (P6b, ADR-0012):
//   registry/snap-overrides.yaml  reviewed placements (CODEOWNERS), read by tools/geo/rivernet
//   registry/rivernet.yaml        GENERATED by scripts/gen-rivernet.ts from the committed fixture;
//                                 read by the registry sync in `migrate`, never by readRegistry
// Owner-audience rows appear here as the station registry identifies them
// (id, river, km): no value, threshold or forecast (invariant 11).

const Slug = z.string().regex(/^[a-z][a-z0-9-]{1,40}$/, 'must be a slug');
const SourceId = z.string().regex(/^[A-Z]{2}-[0-9]+$/, 'must be a source id such as DE-1');
export const StationId = z
  .string()
  .max(80)
  .regex(/^[a-z]{2}\.[a-z0-9-]+\.[A-Za-z0-9._-]+$/, 'must be a station id');
const Reason = z.string().min(1).max(500);
const KmSystem = z.string().min(1).max(80);

/**
 * One reviewed placement. Exactly one of `river` (snap to the nearest edge of
 * that river within `max_m`, default 500 m), `canal` (a canal point: no river,
 * never on a river), `unsnapped`, or `by_km` (a lock-channel gauge whose
 * coordinates lie off the river line: placed by its official km between two
 * anchors of the same river and km system, as a gauge without coordinates).
 */
export const SnapOverride = z
  .strictObject({
    station: StationId,
    river: Slug.optional(),
    canal: z.string().min(1).max(80).optional(),
    unsnapped: z.literal(true).optional(),
    by_km: z.literal(true).optional(),
    km_official: z
      .strictObject({ value: z.number().min(-100).max(2000), system: KmSystem, evidence: Reason })
      .optional(),
    max_m: z.number().positive().max(2000).optional(),
    reason: Reason,
  })
  .refine((o) => [o.river, o.canal, o.unsnapped, o.by_km].filter((x) => x !== undefined).length === 1, {
    message: 'exactly one of river, canal, unsnapped and by_km',
  })
  .refine((o) => o.river !== undefined || (o.km_official === undefined && o.max_m === undefined), {
    message: 'km_official and max_m need a river',
  });
export type SnapOverride = z.infer<typeof SnapOverride>;

/**
 * A water-body label of an owner-audience source mapped to a river. Owner
 * spellings stay out of rivers.yaml `names` (public only, synced into the DB):
 * this table is registry identification and reaches no output.
 */
export const WaterOverride = z.strictObject({
  source: SourceId,
  water_name: z.string().min(1).max(200),
  river: Slug,
  reason: Reason,
});
export type WaterOverride = z.infer<typeof WaterOverride>;

export const SnapOverridesFile = z.strictObject({
  version: z.literal(1),
  stations: z.array(SnapOverride),
  waters: z.array(WaterOverride),
});
export type SnapOverridesFile = z.infer<typeof SnapOverridesFile>;

/** Schema plus uniqueness and river references (`rivers`: the ids of rivers.yaml). */
export function validateSnapOverrides(
  input: unknown,
  rivers: ReadonlySet<string>,
): { problems: string[]; overrides?: SnapOverridesFile } {
  const parsed = SnapOverridesFile.safeParse(input);
  if (!parsed.success) return { problems: [z.prettifyError(parsed.error)] };
  const f = parsed.data;
  const problems: string[] = [];
  const seen = new Set<string>();
  for (const o of f.stations) {
    if (seen.has(o.station)) problems.push(`stations: ${o.station} twice`);
    seen.add(o.station);
    if (o.river !== undefined && !rivers.has(o.river))
      problems.push(`stations: ${o.station}: unknown river ${o.river}`);
  }
  const waters = new Set<string>();
  for (const w of f.waters) {
    const key = `${w.source}\u0000${w.water_name}`;
    if (waters.has(key)) problems.push(`waters: ${w.source} "${w.water_name}" twice`);
    waters.add(key);
    if (!rivers.has(w.river)) problems.push(`waters: ${w.source}: unknown river ${w.river}`);
  }
  return problems.length > 0 ? { problems } : { problems, overrides: f };
}

/**
 * How a station was placed. Placed: override (a reviewed river), name (its
 * published water body), official_km (no coordinates: between two anchors of
 * the same km system). Not placed: canal, unsnapped (reviewed), no_coordinates,
 * water_not_in_rivers, no_edge_within_500m.
 */
export const SNAP_RULES = [
  'override',
  'name',
  'official_km',
  'canal',
  'unsnapped',
  'no_coordinates',
  'water_not_in_rivers',
  'no_edge_within_500m',
] as const;
export type SnapRule = (typeof SNAP_RULES)[number];
export const PLACED_RULES: ReadonlySet<SnapRule> = new Set(['override', 'name', 'official_km']);

const Km = z.number().min(-5000).max(5000);

export const RivernetStation = z.strictObject({
  id: StationId,
  rule: z.enum(SNAP_RULES),
  river: Slug.nullable(),
  reach: ReachId.nullable(),
  km_official: Km.nullable(),
  km_official_system: KmSystem.nullable(),
  km_graph: Km.nullable(),
  km_to_nl_entry: Km.nullable(),
  nl_entry_node: Slug.nullable(),
});
export type RivernetStation = z.infer<typeof RivernetStation>;

export const RivernetReach = z.strictObject({
  id: ReachId,
  river: Slug,
  seq: z.number().int().min(1),
  up_station: StationId.nullable(),
  down_station: StationId.nullable(),
  length_km: z.number().min(0),
  flags: ReachFlags,
  travel_time_h: TravelRange.nullable(),
  travel_time_source: z.string().min(1).max(300).nullable(),
});
export type RivernetReach = z.infer<typeof RivernetReach>;

export const RivernetFile = z.strictObject({
  version: z.literal(1),
  fixture: z.strictObject({
    source_run: z.string().regex(/^https:\/\/github\.com\/mwijkhuisen\/Waterheight\/actions\/runs\/[0-9]+$/),
    ways_sha256: z.string().regex(/^[0-9a-f]{64}$/),
    osm_replication_timestamp: z.iso.datetime(),
  }),
  stations: z.array(RivernetStation),
  reaches: z.array(RivernetReach),
});
export type RivernetFile = z.infer<typeof RivernetFile>;

/** Schema plus references: unique ids, every station reach and river known, reach ids `<river>.<seq>`. */
export function validateRivernet(input: unknown): { problems: string[]; rivernet?: RivernetFile } {
  const parsed = RivernetFile.safeParse(input);
  if (!parsed.success) return { problems: [z.prettifyError(parsed.error)] };
  const f = parsed.data;
  const problems: string[] = [];
  const reaches = new Set<string>();
  for (const r of f.reaches) {
    if (reaches.has(r.id)) problems.push(`reaches: ${r.id} twice`);
    reaches.add(r.id);
    if (r.id !== `${r.river}.${r.seq}`) problems.push(`reaches: ${r.id} is not ${r.river}.${r.seq}`);
  }
  const stations = new Set<string>();
  for (const s of f.stations) {
    if (stations.has(s.id)) problems.push(`stations: ${s.id} twice`);
    stations.add(s.id);
    if (s.reach !== null && !reaches.has(s.reach)) problems.push(`stations: ${s.id}: unknown reach ${s.reach}`);
    if (s.reach !== null && s.river === null) problems.push(`stations: ${s.id}: a reach without a river`);
  }
  for (const r of f.reaches)
    for (const s of [r.up_station, r.down_station])
      if (s !== null && !stations.has(s)) problems.push(`reaches: ${r.id}: unknown station ${s}`);
  return problems.length > 0 ? { problems } : { problems, rivernet: f };
}
