/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Audience = "off" | "owner" | "public";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppMeta {
  key: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface Attribution {
  date_kind: string | null;
  lang: string | null;
  logo_allowed: boolean | null;
  needs_date: boolean;
  ord: number;
  required: boolean;
  source_id: string;
  text: string;
  url: string | null;
}

export interface ClassObs {
  batch_id: Int8 | null;
  level_norm: number | null;
  provider_code: string | null;
  provider_label: string | null;
  source_id: string;
  subject_id: string;
  subject_type: string;
  ts: Timestamp;
}

export interface ForecastRun {
  batch_id: Int8 | null;
  content_hash: Buffer;
  fetched_at: Timestamp;
  first_valid: Timestamp;
  id: Generated<Int8>;
  issued_at: Timestamp | null;
  issued_inferred: Generated<boolean>;
  kind: string;
  last_valid: Timestamp;
  provider_segment_end: Timestamp | null;
  series_id: number;
  source_id: string;
  step: string | null;
}

export interface ForecastValue {
  flags: Generated<number>;
  p05: number | null;
  p10: number | null;
  p25: number | null;
  p30: number | null;
  p50: number | null;
  p70: number | null;
  p75: number | null;
  p90: number | null;
  p95: number | null;
  run_id: Int8;
  valid_ts: Timestamp;
  value: number | null;
  vmax: number | null;
  vmin: number | null;
}

export interface GaugeZero {
  batch_id: Int8;
  datum: string;
  series_id: number;
  valid: string;
  value_m: number;
}

export interface IngestBatch {
  adapter_version: number;
  archive_key: string;
  bytes: Int8 | null;
  error: string | null;
  fetched_at: Timestamp;
  http_status: number | null;
  id: Generated<Int8>;
  loaded_at: Generated<Timestamp>;
  n_changed: Generated<number>;
  n_new: Generated<number>;
  n_rows: Generated<number>;
  n_skipped: Generated<number>;
  parse_status: string;
  sha256: string | null;
  source_id: string;
  spec_id: string;
}

export interface LoadCursor {
  byte_offset: Int8;
  manifest_file: string;
  updated_at: Generated<Timestamp>;
}

export interface Obs {
  batch_id: Int8;
  qc: Generated<number>;
  series_id: number;
  ts: Timestamp;
  value: number;
}

export interface Obs1d {
  bucket: Timestamp;
  n: number;
  qc_or: number;
  series_id: number;
  vavg: number;
  vlast: number;
  vmax: number;
  vmin: number;
}

export interface Obs1h {
  bucket: Timestamp;
  n: number;
  qc_or: number;
  series_id: number;
  vavg: number;
  vlast: number;
  vmax: number;
  vmin: number;
}

export interface ObsLatest {
  batch_id: Int8;
  qc: number;
  series_id: number;
  ts: Timestamp;
  value: number;
}

export interface ObsRevision {
  batch_id: Int8;
  changed_at: Generated<Timestamp>;
  new_qc: number;
  new_value: number;
  old_qc: number;
  old_value: number;
  series_id: number;
  ts: Timestamp;
}

export interface Provider {
  contact: string | null;
  country: string;
  id: string;
  name: string;
  terms_url: string | null;
}

export interface Reach {
  down_station_id: string | null;
  flags: Generated<Json>;
  id: Generated<number>;
  length_km: number | null;
  river_id: string;
  seq: number;
  travel_time_h: string | null;
  travel_time_source: string | null;
  up_station_id: string | null;
}

export interface ReferenceValue {
  basis_label: string | null;
  batch_id: Int8 | null;
  kind: string;
  percentile_convention: string | null;
  period: string | null;
  priority: Generated<number>;
  season_from_md: Generated<number>;
  season_to_md: Generated<number>;
  seen_at: Timestamp | null;
  seen_batch: Int8 | null;
  semantics: string;
  series_id: number;
  source_id: string;
  unit: string;
  valid: string;
  value: number;
}

export interface River {
  confluence_km: number | null;
  id: string;
  names: Generated<Json>;
  osm_relation_id: Int8 | null;
  parent_river_id: string | null;
  wikidata: string | null;
}

export interface Series {
  active: Generated<boolean>;
  audience: Audience | null;
  datum: string | null;
  expected_step: string;
  first_seen: Generated<Timestamp>;
  id: Generated<number>;
  last_seen: Timestamp | null;
  lic_override: Json | null;
  native_step: string;
  native_unit: string;
  provider_key: string;
  quantity: string;
  role: string;
  source_id: string;
  staleness_limit: string;
  station_id: string;
  to_canonical: number;
  value_kind: string | null;
}

export interface Source {
  audience: Audience;
  canary: Generated<boolean>;
  capture_enabled: boolean;
  history_window: Generated<string>;
  id: string;
  lic_api: boolean;
  lic_bulk_export: boolean;
  lic_display: boolean;
  lic_history_export: boolean;
  licence: string | null;
  licence_kind: string | null;
  name: string;
  notes: string | null;
  permission_ref: string | null;
  private_basis: Json | null;
  provider_id: string;
}

export interface SourceHealth {
  circuit_state: string | null;
  consecutive_failures: Generated<number>;
  detail: Generated<Json>;
  lag_p95: string | null;
  last_fetch_ok: Timestamp | null;
  last_new_data: Timestamp | null;
  newest_ts: Timestamp | null;
  quarantine_count: Generated<number>;
  source_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Station {
  country: string;
  flags: Generated<Json>;
  id: string;
  km_official: number | null;
  km_system: string | null;
  km_to_nl_entry: number | null;
  lat: number | null;
  lon: number | null;
  name: string;
  nl_entry_node: string | null;
  operator_provider_id: string | null;
  reach_id: number | null;
  river_id: string | null;
  tier: number;
  water_name: string | null;
}

export interface StationAlias {
  precedence: Generated<number>;
  provider_code: string;
  role: string;
  source_id: string;
  station_id: string;
}

export interface Twin {
  id: string;
  relation: Generated<Json>;
  series_a: number;
  series_b: number;
}

export interface TwinCheck {
  lag_min: number | null;
  max_delta: number | null;
  median_delta: number | null;
  n_aligned: number;
  ok: boolean;
  twin_id: string;
  window_end: Timestamp;
}

export interface WarningArea {
  area_key: string;
  batch_id: Int8 | null;
  geometry_geojson: string | null;
  id: Generated<Int8>;
  issued_at: Timestamp | null;
  label_raw: string | null;
  level_norm: number | null;
  level_raw: string | null;
  name: string | null;
  provider_ref: string | null;
  seen_at: Timestamp | null;
  seen_batch: Int8 | null;
  source_id: string;
  texts: Json | null;
  valid: string;
}

export interface DB {
  app_meta: AppMeta;
  attribution: Attribution;
  class_obs: ClassObs;
  forecast_run: ForecastRun;
  forecast_value: ForecastValue;
  gauge_zero: GaugeZero;
  ingest_batch: IngestBatch;
  load_cursor: LoadCursor;
  obs: Obs;
  obs_1d: Obs1d;
  obs_1h: Obs1h;
  obs_latest: ObsLatest;
  obs_revision: ObsRevision;
  provider: Provider;
  reach: Reach;
  reference_value: ReferenceValue;
  river: River;
  series: Series;
  source: Source;
  source_health: SourceHealth;
  station: Station;
  station_alias: StationAlias;
  twin: Twin;
  twin_check: TwinCheck;
  warning_area: WarningArea;
}
