// Regenerates docs/classification.md (P7b, ADR-0009) from the class crosswalk of packages/core: the document is a
// function of the code's table, so a changed row is an edit of crosswalk.ts and a run of this script.
//
//   node scripts/gen-classification.ts            # rewrite docs/classification.md
//   node scripts/gen-classification.ts --check    # exit 1 if the committed file differs
//
// Nothing here reads apps/ or any data: only table rows, never a threshold value (invariant 11).

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  AGENCY,
  AREA_SCALE,
  CLASS_WINDOW_MIN,
  CROSSWALK,
  type CrosswalkRow,
  HUBEAU_ZERO_SOURCES,
  REFERENCE_ROLES,
  type ReferenceRole,
  TO_NAP,
  TREND_BAND,
} from '../packages/core/src/index.ts';

export const DOC_PATH = join(import.meta.dirname, '..', 'docs/classification.md');

const cell = (s: string) => s.replaceAll('\\', '\\\\').replaceAll('|', '\\|').replace(/\r?\n/g, ' ');
const table = (head: string[], rows: string[][]) =>
  [head, head.map(() => '---'), ...rows].map((r) => `| ${r.map(cell).join(' | ')} |`).join('\n');

const audience = (r: { audience: 'public' | 'owner'; gated?: true }) =>
  r.gated ? 'gated (P13)' : r.audience === 'owner' ? 'owner view only' : 'public';

const ATTACH: Readonly<Record<string, string>> = {
  'DE-6': 'Region (polygon) alerts: the stations inside; River lines are not attached',
  'FR-5': 'TronEntVigiCru section table (registry/vigicrues-sections.yaml)',
  'CH-5': 'river:<n> and lake:<n> to station ch.bafu.<n>; hydro_region polygon to the stations inside',
  'LU-5': 'zone polygon: the stations inside',
  'DE-10': 'region polygon: the stations inside (gated, P13)',
};

const gaugeRow = (r: CrosswalkRow) => [
  r.source,
  r.scale,
  r.code,
  r.level,
  r.basis,
  r.group,
  audience(r),
  r.noFlood ? 'no flood: interval low..normal, point normal' : (r.flag ?? ''),
];
const areaRow = (r: CrosswalkRow) => [
  r.source,
  r.scale,
  r.code,
  r.level,
  r.basis,
  r.group,
  audience(r),
  ATTACH[r.source] ?? '',
  r.noFlood ? 'no flood: interval low..normal, point normal' : (r.flag ?? ''),
];

const RULE = { '>=': '≥ → ', '<=': '≤ → ', '<': '< → ' } as const;
const refRow = (r: ReferenceRole) => [
  r.source,
  r.kind,
  r.op === null ? 'shown, never classifies' : `${RULE[r.op]}${r.level}`,
  r.basis,
  r.group ?? '',
  r.form ?? '',
  audience(r),
  [r.convention ? `convention ${r.convention}` : '', r.flag ?? ''].filter(Boolean).join('; '),
];

const nap = (d: string) => {
  const t = TO_NAP[d as keyof typeof TO_NAP];
  return t.converted
    ? [d, `${t.offsetM >= 0 ? '+' : ''}${t.offsetM}`, `± ${t.uncertaintyM}`, t.source]
    : [d, 'not converted', '', t.reason];
};

export function generate(): string {
  const gauge = CROSSWALK.filter((r) => r.group !== 'area');
  const area = CROSSWALK.filter((r) => r.group === 'area');
  const w = CLASS_WINDOW_MIN;
  const windows = Object.entries(w)
    .map(([s, m]) => `${s} ${m} min`)
    .join(', ');
  return `<!-- GENERATED by scripts/gen-classification.ts from packages/core/src/crosswalk.ts. Do not edit: change the table and run it again (CI fails on a difference). -->

# Classification

Every value gets one state on the scale \`no_ref < low < normal < elevated < high < extreme\` and the basis it was taken from (ADR-0009). \`no_ref\` is never a guess: a station without a deciding reference gets no neighbour, default or interpolated threshold.

## Rules

- **Priority groups:** operational (the agency's gauge class, then its thresholds), then statistical references, then the provider's display classes (NL-4). Within operational the published class comes first: our comparison of the value with the thresholds can lag it or disagree at a boundary (BAFU danger level 2 with Q under WL2 is elevated). Area classes apply only where no gauge state exists.
- **Combining:** each candidate gives an interval on low..extreme and, where it decides, a point level. Candidates are taken in group order; each one narrows the interval when it intersects it. One that does not is outranked (the higher priority wins), but the interval collapses to the edge nearest to it: below AGE orange with HQ10 passed is elevated, so a higher value never gives a lower level. The state is the interval when one level is left, else the first point inside it, else \`no_ref\`. The basis is the first candidate whose point is the state; after a collapse that no point names, both decisive candidates (source, kind and measure of the one that narrowed the interval, both refs joined by \`/\` and both labels by \` / \`: \`AGE < orange / AGE HQ10\`); else the last one that narrowed the interval. A scale's "below its lowest level" reads \`< Info 1\` in the label.
- **Set forms:** \`scale\` is an agency's full scale (below its lowest level is normal); \`stats\` are statistics, not warnings (normal only between a low bound and an \`elevated\` bound); \`percentile\` is low at or below the low bound, else normal, never an alert level.
- **No-flood classes** (marked in the tables) give only "not elevated": interval low..normal, point normal. Classes marked \`no_ref\` give no candidate.
- **Gauge beats area:** an area class colours a value only when its gauge state is \`no_ref\` (\`section: true\`); otherwise it is returned beside the state. The highest area level wins. A gauge class reaches the station's series of its basis quantity, else the station's other series. The Basis column names a row's usual quantity; a state reports what it measures from the series it classifies: \`stage\`, \`level\` (an absolute level: a lake, a NAP level series), \`discharge\` or \`area\` (an NL-4 class on a Q series is discharge, a BAFU danger level on a lake is level: KG-185).
- **Tidal** reaches (D12) are classed from operational candidates only. **Impounded** stage series skip the statistical low bounds.
- **Units:** a reference counts only in cm (H) or m³/s (Q).
- **Per audience:** the public run never uses an owner-view row, even if one is handed in.
- **Labels:** a basis label is the agency and its reference or class (\`WSV MNW 2010–2020\`, \`LHP RP:0\`), the NL-4 workbook label as published (\`Licht verhoogd (>200cm)\`; the source names RWS Waterinfo and the page adds the legend's disclaimer) or the agency and the area's name. Provider text is inert, and a label is cut at 700 characters, a ref at 200.
- **Coverage report (D10):** per country, the tier-1 stations with a state other than \`no_ref\` (\`classed\`), of them those classed only through an area (\`by_section\`), and the first-release stations whose state comes from a source that needs no permission. The default map mode is \`state\` when (classed − by_section) / stations is at least 0.6, else \`dh\`: Vigicrues green and LU-Alert information exist at all times and do not count. In the owner report an LU-4 or BE-3 basis counts as a source that needs no permission (personal-use terms, catalogue §0.8); the public report never sees them.
- **Freshness:** for the current bucket a class or area counts only while its source's last successful fetch is recent: ${windows}. An earlier \`t\` uses the stored rows.
- **Boundaries:** ≥ is reached at the threshold, ≤ is low at the bound, < is strictly below. NL-4 classes hold [From, To), and the lowest Priority wins where bands overlap.
- **Percentile conventions (C31):** SPW percentiles are non-exceedance (P90 above the mean), HIC percentiles are exceedance (P10 above P90). A row with the other convention is not that reference, and a set that contradicts its convention is not used.
- **Δh trend:** steady within H ± ${TREND_BAND.cm} cm and Q ± max(${TREND_BAND.qAbs} m³/s, ${TREND_BAND.qRel * 100} % of the start value).
- **≈ m NAP (D16):** shown only for a stage with a gauge zero in a converted datum, or a level in its own datum. Never for IGN69 or NGF1884 zeros or for zeros of ${[...HUBEAU_ZERO_SOURCES].join(', ')} (Hub'Eau metadata), which are shown as published and unverified.

${table(['Datum', 'Offset to NAP (m)', 'Uncertainty (m)', 'Basis'], Object.keys(TO_NAP).map(nap))}

## Gauge classes

${table(['Source', 'Scale', 'Code', 'Level', 'Basis', 'Group', 'Audience', 'Note'], gauge.map(gaugeRow))}

## Area classes

${table(
  ['Source', 'Scale', 'Code', 'Level', 'Basis', 'Group', 'Audience', 'Attaches to stations', 'Note'],
  area.map(areaRow),
)}

Area scales: ${Object.entries(AREA_SCALE)
    .map(([s, k]) => `${s} ${k}`)
    .join(', ')}.

## Reference kinds

${table(['Source', 'Kind', 'Rule', 'Basis', 'Group', 'Set form', 'Audience', 'Note'], REFERENCE_ROLES.map(refRow))}

## Agencies in basis labels

${table(
  ['Source', 'Agency'],
  Object.entries(AGENCY).map(([s, a]) => [s, a]),
)}
`;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    console.error('usage: node scripts/gen-classification.ts [--check]');
    process.exit(64);
  }
  const text = generate();
  if (args.length === 0) writeFileSync(DOC_PATH, text);
  else if (readFileSync(DOC_PATH, 'utf8') !== text) {
    console.error('gen-classification: docs/classification.md is stale; run node scripts/gen-classification.ts');
    process.exitCode = 1;
  }
}
