// Regenerates registry/rivernet.yaml (P6b): every registry station placed on the
// river graph of the COMMITTED fixture (tools/geo/fixtures/rivernet.*), with the
// same code geo.yml runs (tools/geo/rivernet/place.ts), and the public reaches.
// The registry sync in `migrate` stores it (river, reach, km_official and its
// label, km_to_nl_entry, nl_entry_node); km_graph stays in the file.
//
//   node scripts/gen-rivernet.ts            # rewrite registry/rivernet.yaml
//   node scripts/gen-rivernet.ts --check    # exit 1 if the committed file differs
//
// A newer geo release is adopted by refreshing the fixture from that run's
// `rivernet-fixture` artifact, updating FIXTURE_RUN and running this script
// (docs/runbooks/geo-refresh.md). Owner-audience rows appear as the station
// registry identifies them: id, river, reach and km (invariant 11).

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { type RivernetFile, validateRivernet } from '../packages/contracts/src/rivernet.ts';
import { buildFromFiles, readRivers } from '../tools/geo/rivernet/build.ts';
import { place, readOverrides } from '../tools/geo/rivernet/place.ts';
import { readStations } from '../tools/geo/rivernet/stations.ts';

const root = join(import.meta.dirname, '..');
const FX = join(root, 'tools/geo/fixtures');
export const FIXTURE_RUN = 'https://github.com/mwijkhuisen/Waterheight/actions/runs/38072080277';
export const RIVERNET_PATH = join(root, 'registry/rivernet.yaml');

const HEADER = `# GENERATED by scripts/gen-rivernet.ts from the committed river-graph fixture, registry/rivers.yaml,
# registry/snap-overrides.yaml and registry/stations/ (P6b, ADR-0012). Do not edit: change the inputs and
# run it again (CI fails on a difference). Read by the registry sync in \`migrate\`, never by readRegistry.
# stations: every registry station; rule = how it was placed (override, name, official_km) or why not
#   (canal, unsnapped, no_coordinates, water_not_in_rivers, no_edge_within_500m); km_official is the
#   operator's km (km_official_system its label), km_graph the km along its river from the river's
#   sources, km_to_nl_entry the km to its NL entry node (negative below it). Owner-audience rows identify
#   the station only (river, reach, km). reaches: cut at public stations only; id <river>.<seq>.
`;

export async function generate(): Promise<string> {
  const ways = join(FX, 'rivernet.ways.geojsonseq');
  const build = await buildFromFiles({
    ways,
    relations: join(FX, 'rivernet.relations.opl'),
    provenance: join(FX, 'rivernet.provenance.json'),
  });
  const rivers = readRivers();
  const placed = place(build.edges, rivers, readStations(), readOverrides(rivers));
  const osm = (build.graph as { osm: { replication_timestamp: string } }).osm.replication_timestamp;
  const file: RivernetFile = {
    version: 1,
    fixture: {
      source_run: FIXTURE_RUN,
      ways_sha256: createHash('sha256').update(readFileSync(ways)).digest('hex'),
      osm_replication_timestamp: osm,
    },
    stations: [...placed.stations]
      .sort((a, b) => (a.id < b.id ? -1 : 1))
      .map((s) => ({
        id: s.id,
        rule: s.rule,
        river: s.river,
        reach: s.reach,
        km_official: s.km_official,
        km_official_system: s.km_official_system,
        km_graph: s.km_graph,
        km_to_nl_entry: s.km_to_nl_entry,
        nl_entry_node: s.nl_entry_node,
      })),
    reaches: placed.reaches.map((r) => ({
      id: r.id,
      river: r.river,
      seq: r.seq,
      up_station: r.up_station,
      down_station: r.down_station,
      length_km: Math.round(r.length_m) / 1000,
      flags: r.flags,
      travel_time_h: r.travel_time_h,
      travel_time_source: r.travel_time_source,
    })),
  };
  const { problems } = validateRivernet(file);
  if (problems.length > 0) throw new Error(`gen-rivernet: ${problems.slice(0, 5).join('; ')}`);
  // One JSON flow mapping per line: valid YAML, diffable per station and reach.
  const lines = (rows: readonly object[]) => rows.map((r) => `  - ${JSON.stringify(r)}\n`).join('');
  return `${HEADER}version: 1\nfixture: ${JSON.stringify(file.fixture)}\nstations:\n${lines(file.stations)}reaches:\n${lines(file.reaches)}`;
}

if (import.meta.main) {
  const text = await generate();
  if (!process.argv.includes('--check')) writeFileSync(RIVERNET_PATH, text);
  else if (readFileSync(RIVERNET_PATH, 'utf8') !== text) {
    console.error('gen-rivernet: registry/rivernet.yaml is stale; run node scripts/gen-rivernet.ts');
    process.exitCode = 1;
  }
}
