// P10b: the Method page's crosswalk table (apps/web/src/features/pages/method.gen.ts), generated from
// packages/core/src/crosswalk.ts. Only rows a public view may show go in: a row of `audience: public`, not `gated`,
// of a source that registry/sources.yaml lists as public. The owner and permission sources' rows, their flags and
// their agencies stay out of the public bundle (the root of @rws/core is banned in the web anyway). A reference
// role carries no `flag` and no `convention`; AGENCY keeps the sources that have a row in the file.
// Usage: node scripts/gen-web-method.ts [--check] [repo-root]   (--check diffs and exits 1)
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parse } from 'yaml';
import { AGENCY, CROSSWALK, REFERENCE_ROLES } from '../packages/core/src/crosswalk.ts';

export const METHOD_FILE = 'apps/web/src/features/pages/method.gen.ts';

function biomeFormat(root: string, path: string, source: string): string {
  const r = spawnSync(join(root, 'node_modules/.bin/biome'), ['format', `--stdin-file-path=${path}`], {
    input: source,
    encoding: 'utf8',
    cwd: root,
  });
  if (r.status !== 0) throw new Error(`gen-web-method: biome format failed for ${path}`);
  return r.stdout;
}

export function generate(root: string): string {
  const reg = parse(readFileSync(join(root, 'registry/sources.yaml'), 'utf8')) as {
    sources: { id: string; audience: string }[];
  };
  const isPublic = new Set(reg.sources.filter((s) => s.audience === 'public').map((s) => s.id));
  const shown = (r: { source: string; audience: string; gated?: true }) =>
    r.audience === 'public' && r.gated !== true && isPublic.has(r.source);
  const classes = CROSSWALK.filter(shown).map((r) => ({
    source: r.source,
    scale: r.scale,
    code: r.code,
    level: r.level,
    basis: r.basis,
    group: r.group,
    noFlood: r.noFlood === true,
  }));
  const references = REFERENCE_ROLES.filter(shown).map((r) => ({
    source: r.source,
    kind: r.kind,
    op: r.op,
    level: r.level,
    basis: r.basis,
    group: r.group,
    form: r.form,
    short: r.short,
  }));
  const inFile = new Set([...classes, ...references].map((r) => r.source));
  const agencies = Object.fromEntries(Object.entries(AGENCY).filter(([source]) => inFile.has(source)));
  const lit = (v: unknown) => JSON.stringify(v, null, 2);
  return biomeFormat(
    root,
    'method.gen.ts',
    `// GENERATED by scripts/gen-web-method.ts from packages/core/src/crosswalk.ts and registry/sources.yaml. Do not edit.
// The public, ungated rows only: the Method page's class crosswalk and reference roles (catalogue §4.9, ADR-0009).

export type MethodClass = {
  source: string;
  scale: string;
  code: string;
  level: 'low' | 'normal' | 'elevated' | 'high' | 'extreme' | 'no_ref';
  basis: 'stage' | 'discharge' | 'area';
  group: 'operational' | 'statistical' | 'provider_class' | 'area';
  /** "No flood" (LHP 0, BAFU 1, Vigicrues green, LU-Alert information): only "not elevated". */
  noFlood: boolean;
};

export type MethodReference = {
  source: string;
  kind: string;
  /** A value at or above, at or below, or below the reference reaches the level; null: shown, never classifies. */
  op: '>=' | '<=' | '<' | null;
  level: 'low' | 'normal' | 'elevated' | 'high' | 'extreme' | null;
  basis: 'stage' | 'discharge' | 'area';
  group: 'operational' | 'statistical' | null;
  form: 'scale' | 'stats' | 'percentile' | null;
  short: string;
};

export const METHOD_CLASSES: readonly MethodClass[] = ${lit(classes)};

export const METHOD_REFERENCES: readonly MethodReference[] = ${lit(references)};

/** The agency named in a basis label, for the sources above. */
export const METHOD_AGENCIES: Readonly<Record<string, string>> = ${lit(agencies)};
`,
  );
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const root = resolve(args.find((a) => !a.startsWith('--')) ?? join(import.meta.dirname, '..'));
  const content = generate(root);
  let have = '';
  try {
    have = readFileSync(join(root, METHOD_FILE), 'utf8');
  } catch {}
  if (have !== content) {
    if (check) {
      console.error(`gen-web-method: ${METHOD_FILE} is out of date (run: node scripts/gen-web-method.ts)`);
      process.exit(1);
    }
    writeFileSync(join(root, METHOD_FILE), content);
  }
  console.log(`gen-web-method: ${check ? 'OK' : 'written'} (${METHOD_FILE})`);
}
