#!/usr/bin/env bash
# Offline tests of rws-backup, rws-restore-drill, rws-tick, rws-resolvers and
# the shared ops.json writer (issue #16 P1b). docker, nft, getent and curl are
# stubs; jq, zstd, sha256sum, shuf and flock are real. The drill runs against
# a synthetic raw archive (generated bytes, never provider data).
# Usage: deploy/tests/backup.test.sh
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
bin=$(cd "$here/../bin" && pwd)
T=$(mktemp -d)
trap 'rm -rf -- "$T"' EXIT
readonly KEY=testPingKey_0123456789ab
readonly ORIG_PATH=$PATH
failures=0 labels=0

# ---------------------------------------------------------------- stubs
mkdir -p "$T/stubs"
cat >"$T/stubs/curl" <<'STUB'
#!/usr/bin/env bash
printf 'curl %s\n' "$*" >>"$FIX/calls"
body=''
while (($#)); do [[ $1 == --data-raw ]] && body=$2; shift; done
IFS= read -r line
line=${line#url = \"}; line=${line%\"}
printf '%s %s\n' "$line" "$body" >>"$FIX/pings"
STUB
cat >"$T/stubs/nft" <<'STUB'
#!/usr/bin/env bash
printf 'nft %s\n' "$*" >>"$FIX/calls"
cat >>"$FIX/nft"
STUB
cat >"$T/stubs/getent" <<'STUB'
#!/usr/bin/env bash
case $1 in
  ahostsv4) printf '192.0.2.10 STREAM %s\n192.0.2.10 DGRAM\n192.0.2.11 STREAM\n' "$2" ;;
  ahostsv6) printf '2001:db8::10 STREAM %s\n::ffff:192.0.2.10 STREAM\n' "$2" ;;
esac
STUB
cat >"$T/stubs/docker" <<'STUB'
#!/usr/bin/env bash
# `compose run ... backup <restic args>`: backup/init/snapshots/restore against $FIX.
set -euo pipefail
printf 'docker %s\n' "$*" >>"$FIX/calls"
case $1 in
  ps) cat "$FIX/unhealthy" 2>/dev/null || true; exit 0 ;;
  restart) exit 0 ;;
  compose) ;;
  *) exit 0 ;;
esac
while (($#)) && [[ $1 != backup ]]; do shift; done
shift
drill=$RWS_SRV/backup/drill
case $1 in
  init) ;;
  backup)
    [[ ! -e $FIX/backup-fails ]] || exit 1
    [[ ! -e $FIX/backup-unreadable ]] || exit 3
    ;;
  snapshots) printf '[{"id":"%s","time":"2026-09-02T00:00:00.123456789Z"}]\n' "$(printf 'a%.0s' {1..64})" ;;
  ls)
    # restic ls --json: the snapshot, then one node per entry.
    printf '{"struct_type":"snapshot","id":"x"}\n{"name":"_manifest","type":"dir","path":"/data/raw/_manifest"}\n'
    for f in "$FIX/raw/_manifest"/*; do
      printf '{"name":"%s","type":"file","path":"/data/raw/_manifest/%s"}\n' "${f##*/}" "${f##*/}"
    done
    ;;
  restore)
    grep '/_manifest/' "$drill/.include" >>"$FIX/restored-manifests" || true
    while IFS= read -r path; do
      src=$FIX/raw/${path#/data/raw/}
      [[ -f $src ]] || continue
      mkdir -p "$(dirname "$drill$path")"
      cp "$src" "$drill$path"
    done <"$drill/.include"
    victim=$(find "$drill/data/raw" -name '*.zst' -print -quit)
    if [[ -e $FIX/corrupt && -n $victim ]]; then printf 'x' | zstd -q -c >"$victim"; fi
    ;;
  *) exit 2 ;;
esac
STUB
chmod +x "$T/stubs"/*

# ---------------------------------------------------------------- fixtures
# A synthetic archive: 120 objects recorded before the snapshot (2026-09-02T00:00Z),
# and 5 lines recorded after it whose objects the snapshot does not have, in the
# newest manifest day; and 3 older days of 10 objects each.
mkobject() {
  local dir=$1 day=$2 i=$3 start=$4 store=$5 body sha key
  body="synthetic object $day $i $RANDOM$RANDOM"
  sha=$(printf '%s' "$body" | sha256sum | cut -d' ' -f1)
  key=$(printf 'raw/NL-1/nl-1-obs-key/%s/%06dZ-%s.zst' "${day//-//}" "$i" "${sha:0:16}")
  if ((store)); then
    mkdir -p "$(dirname "$dir/${key#raw/}")"
    printf '%s' "$body" | zstd -q -c >"$dir/${key#raw/}"
  fi
  jq -cn --arg key "$key" --arg sha "$sha" --arg start "$start" \
    '{v: 1, source: "NL-1", spec: "nl-1-obs-key", key: $key, sha256: $sha, fetched_at: {start: $start, end: $start}}'
  # a dup line (no object) must never be sampled
  jq -cn --arg sha "$sha" '{v: 1, key: null, dup_of: "x", sha256: $sha, fetched_at: {start: "2026-09-01T00:00:00Z"}}'
}
mkarchive() {
  local dir=$1 i day
  mkdir -p "$dir/_manifest"
  for i in $(seq 1 125); do
    if ((i <= 120)); then mkobject "$dir" 2026-09-01 "$i" 2026-09-01T12:00:00.000Z 1; else
      mkobject "$dir" 2026-09-01 "$i" 2026-09-02T00:05:00.000Z 0
    fi
  done >"$dir/_manifest/2026-09-01.jsonl"
  for day in 2026-08-29 2026-08-30 2026-08-31; do
    for i in $(seq 1 10); do mkobject "$dir" "$day" "$i" "${day}T12:00:00.000Z" 1; done >"$dir/_manifest/$day.jsonl"
  done
}

setup() {
  C=$(mktemp -d "$T/case.XXXX")
  mkdir -p "$C"/{state/releases/r,etc/secrets,srv/public/ops,srv/backup/drill,lock,fix}
  ln -s releases/r "$C/state/active"
  export FIX=$C/fix RWS_STATE_DIR=$C/state RWS_ETC=$C/etc RWS_SRV=$C/srv RWS_LOCK_DIR=$C/lock
  export PATH=$T/stubs:$ORIG_PATH
  cat >"$C/etc/rws.env" <<EOF
RWS_DOMAIN=rivierstanden.example
RWS_BACKUP=on
RWS_RESTIC_REPOSITORY=s3:https://s3.bucket.example/rws-raw/restic
EOF
  printf '%s\n' "$KEY" >"$C/etc/secrets/hc_ping_key"
  touch "$FIX/calls" "$FIX/pings" "$FIX/nft"
  mkarchive "$FIX/raw"
}
run() {
  rc=0
  "$bin/$1" "${@:2}" >"$C/out" 2>&1 || rc=$?
}
ops() { jq -c "$1" "$RWS_SRV/public/ops/ops.json"; }

fail() {
  echo "  FAIL: $*" >&2
  sed 's/^/  | /' "$C/out" >&2
  failures=$((failures + 1))
}
expect_rc() { [[ $rc == "$1" ]] || fail "exit $rc, expected $1"; }
expect_eq() { [[ $1 == "$2" ]] || fail "got '$1', expected '$2'"; }
expect_grep() { grep -qE -- "$1" "$2" || fail "no line matching /$1/ in ${2##*/}"; }
expect_no_grep() { ! grep -qE -- "$1" "$2" || fail "unexpected /$1/ in ${2##*/}"; }
case_() {
  labels=$((labels + 1))
  printf 'case %s\n' "$*"
}

# ---------------------------------------------------------------- cases
case_ "backups off: nothing runs, exit 0"
setup
sed -i 's/RWS_BACKUP=on/RWS_BACKUP=off/' "$RWS_ETC/rws.env"
run rws-backup
expect_rc 0
expect_grep "backups are off" "$C/out"
expect_no_grep . "$FIX/calls"

case_ "malformed repository: fails loudly"
setup
sed -i 's#^RWS_RESTIC_REPOSITORY=.*#RWS_RESTIC_REPOSITORY=s3:http://s3.bucket.example/rws#' "$RWS_ETC/rws.env"
run rws-backup
expect_rc 1
expect_grep "must look like s3:https" "$C/out"

case_ "backup: bucket addresses allowed, restic run, last_backup set, pinged"
setup
run rws-backup
expect_rc 0
expect_grep "add element inet rws backup4 \{ 192\.0\.2\.10,192\.0\.2\.11 \}" "$FIX/nft"
expect_grep "add element inet rws backup6 \{ 2001:db8::10 \}" "$FIX/nft"
expect_no_grep "::ffff:" "$FIX/nft"
expect_grep "compose .* run --rm --no-deps -T backup backup --host rws --exclude /data/raw/\.tmp --exclude \*\.json\.\[0-9\]\*\.tmp /data/raw$" "$FIX/calls"
expect_eq "$(ops 'keys')" '["disk_pct","drill","generated_at","last_backup"]'
[[ $(ops '.last_backup') =~ ^\"20[0-9]{2}- ]] || fail "last_backup not set"
expect_grep "/backup/start " "$FIX/pings"
expect_grep "/backup ok$" "$FIX/pings"
expect_no_grep "$KEY" "$FIX/calls"
[[ $(stat -c %a "$RWS_SRV/public/ops/ops.json") == 644 ]] || fail "ops.json is not 0644"

case_ "restic exit 3 (some files unreadable, snapshot saved): last_backup set, success ping with a fixed code"
setup
touch "$FIX/backup-unreadable"
run rws-backup
expect_rc 0
[[ $(ops '.last_backup') =~ ^\"20[0-9]{2}- ]] || fail "last_backup not set"
expect_grep "/backup files_unreadable$" "$FIX/pings"
expect_no_grep "/backup/fail" "$FIX/pings"
expect_grep "could not read some files" "$C/out"

case_ "backup failure: /fail with a fixed code, last_backup untouched"
setup
touch "$FIX/backup-fails"
run rws-backup
expect_rc 1
expect_grep "/backup/fail backup_failed$" "$FIX/pings"
[[ ! -e $RWS_SRV/public/ops/ops.json ]] || fail "ops.json written after a failed backup"

case_ "restore drill: 100 of 100, counts only, lines newer than the snapshot never sampled"
setup
run rws-restore-drill --force
expect_rc 0
expect_eq "$(wc -l <"$FIX/restored-manifests")" 3
expect_grep "^/data/raw/_manifest/2026-09-01\.jsonl$" "$FIX/restored-manifests"
expect_grep "backup ls --json a{64} /data/raw/_manifest$" "$FIX/calls"
expect_eq "$(tail -n 1 "$C/out")" "restore drill: sampled 100, matched 100"
expect_eq "$(ops '.drill | [.sampled, .matched]')" '[100,100]'
expect_grep "/restore-drill ok$" "$FIX/pings"
grep -c . "$RWS_SRV/backup/drill" >/dev/null 2>&1 || true
[[ -z $(find "$RWS_SRV/backup/drill" -mindepth 1) ]] || fail "the scratch directory was not emptied"
grep -q 'T000005Z\|2026-09-02T00:05' "$C/out" && fail "a line newer than the snapshot leaked into the output"
expect_no_grep "NL-1|nl-1" "$C/out"

case_ "restore drill: one corrupted object fails, /fail, result recorded"
setup
touch "$FIX/corrupt"
run rws-restore-drill --force
expect_rc 1
expect_eq "$(ops '.drill | [.sampled, .matched]')" '[100,99]'
expect_grep "/restore-drill/fail mismatch$" "$FIX/pings"
[[ -z $(find "$RWS_SRV/backup/drill" -mindepth 1) ]] || fail "the scratch directory was not emptied"

case_ "restore drill: too few objects before the snapshot"
setup
head -n 100 "$FIX/raw/_manifest/2026-09-01.jsonl" >"$FIX/m" && mv "$FIX/m" "$FIX/raw/_manifest/2026-09-01.jsonl"
rm "$FIX/raw/_manifest/2026-08-29.jsonl"
run rws-restore-drill --force
expect_rc 1
expect_grep "/restore-drill/fail too_few_objects$" "$FIX/pings"

case_ "restore drill: skipped when the last one is recent, unless --force"
setup
printf '{"generated_at":"x","last_backup":null,"drill":{"at":"%s","sampled":100,"matched":100},"disk_pct":null}\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$RWS_SRV/public/ops/ops.json"
run rws-restore-drill
expect_rc 0
expect_grep "next one due later" "$C/out"
expect_no_grep "^docker" "$FIX/calls"

case_ "tick: disk_pct written, unhealthy containers restarted, other keys kept"
setup
printf '{"generated_at":"x","last_backup":"2026-09-01T00:00:00Z","drill":null,"disk_pct":null,"extra":"dropped"}\n' \
  >"$RWS_SRV/public/ops/ops.json"
echo rws-capture-1 >"$FIX/unhealthy"
run rws-tick
expect_rc 0
[[ $(ops '.disk_pct') =~ ^[0-9]+$ ]] || fail "disk_pct not a number"
expect_eq "$(ops '.last_backup')" '"2026-09-01T00:00:00Z"'
expect_eq "$(ops 'keys')" '["disk_pct","drill","generated_at","last_backup"]'
expect_grep "docker restart rws-capture-1" "$FIX/calls"

case_ "ops.json writer: a corrupt file is replaced, never kept"
setup
echo 'not json' >"$RWS_SRV/public/ops/ops.json"
run rws-tick
expect_rc 0
expect_eq "$(ops 'keys')" '["disk_pct","drill","generated_at","last_backup"]'

case_ "resolvers: servers from resolv.conf, the systemd stub skipped"
setup
printf 'nameserver 127.0.0.53\noptions edns0\n' >"$C/stub.conf"
printf 'nameserver 192.0.2.53\nnameserver 2001:db8::53%%eth0\nnameserver 127.0.0.1\n' >"$C/real.conf"
RWS_RESOLV_CONF=$C/real.conf run rws-resolvers --dry-run
expect_rc 0
expect_grep "add element inet rws resolvers4 \{ 192\.0\.2\.53 \}" "$C/out"
expect_grep "add element inet rws resolvers6 \{ 2001:db8::53 \}" "$C/out"
expect_no_grep "127\.0\.0" "$C/out"

echo "$labels cases, $failures failures"
((failures == 0))
