#!/usr/bin/env bash
# Offline tests of rws-backup (with the nightly database dump), rws-restore-drill,
# rws-tick, rws-resolvers, rws-status-copy, object-lock-prune.sh and the shared
# ops.json writer (issue #16 P1b, P2a). docker, nft, getent, curl and chown are
# stubs, and date answers `date -u +%s` from $FIX/now when it exists; jq, zstd,
# sha256sum, shuf, flock and openssl are real. The drill runs against a
# synthetic raw archive (generated bytes, never provider data).
# Usage: deploy/tests/backup.test.sh
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
bin=$(cd "$here/../bin" && pwd)
T=$(mktemp -d)
trap 'rm -rf -- "$T"' EXIT
readonly KEY=testPingKey_0123456789ab
readonly ORIG_PATH=$PATH
failures=0 labels=0

# ---------------------------------------------------------------- stubs
mkdir -p "$T/stubs"
cat >"$T/stubs/curl" <<'STUB'
#!/usr/bin/env bash
# A ping (its URL in the config on stdin) goes to $FIX/pings; an S3 call of
# object-lock-prune.sh (the URL in argv) gets $FIX/s3-lock or a fixed answer.
printf 'curl %s\n' "$*" >>"$FIX/calls"
body='' method=GET url=''
while (($#)); do
  case $1 in
    --data-raw) body=$2; shift ;;
    -X) method=$2; shift ;;
    https://*) url=$1 ;;
  esac
  shift
done
IFS= read -r line
if [[ -z $url ]]; then
  line=${line#url = \"}; line=${line%\"}
  printf '%s %s\n' "$line" "$body" >>"$FIX/pings"
  exit 0
fi
case "$method $url" in
  "GET "*'?versions&prefix='*)
    p=${url##*prefix=}
    printf '<ListVersionsResult><Version><Key>%sa</Key><VersionId>v1</VersionId></Version><Version><Key>%sb</Key><VersionId>v2</VersionId></Version></ListVersionsResult>' "$p" "$p"
    ;;
  "GET "*'?object-lock') cat "$FIX/s3-lock" ;;
  "GET "*'?retention&versionId='*)
    printf '<Retention><Mode>COMPLIANCE</Mode><RetainUntilDate>%s</RetainUntilDate></Retention>' "$(date -u -d '+30 days' +%Y-%m-%dT%H:%M:%SZ)"
    ;;
  "DELETE "* | "PUT "*) printf 403 ;;
esac
STUB
cat >"$T/stubs/nft" <<'STUB'
#!/usr/bin/env bash
# `nft -f -` batches go to $FIX/nft; table inet rws exists unless $FIX/no-table does.
printf 'nft %s\n' "$*" >>"$FIX/calls"
case $* in
  '-f -') cat >>"$FIX/nft" ;;
  'list table inet rws') [[ ! -e $FIX/no-table ]] ;;
  '-f '*) rm -f "$FIX/no-table" ;;
esac
STUB
cat >"$T/stubs/systemctl" <<'STUB'
#!/usr/bin/env bash
# rws-status-copy.path is active unless $FIX/path-down exists; start re-arms it.
printf 'systemctl %s\n' "$*" >>"$FIX/calls"
case $1 in
  is-active) [[ ! -e $FIX/path-down ]] ;;
  start) rm -f "$FIX/path-down" ;;
esac
STUB
cat >"$T/stubs/getent" <<'STUB'
#!/usr/bin/env bash
case $1 in
  ahostsv4) printf '192.0.2.10 STREAM %s\n192.0.2.10 DGRAM\n192.0.2.11 STREAM\n' "$2" ;;
  ahostsv6) printf '2001:db8::10 STREAM %s\n::ffff:192.0.2.10 STREAM\n' "$2" ;;
esac
STUB
cat >"$T/stubs/docker" <<'STUB'
#!/usr/bin/env bash
# `compose config --services`: the lines of $FIX/services. `compose exec -T db
# pg_dumpall|pg_dump`: a synthetic dump, nothing with $FIX/dump-empty, exit 1
# with $FIX/dump-fails. `compose run ... backup <restic args>`:
# backup/init/snapshots/restore against $FIX.
set -euo pipefail
printf 'docker %s\n' "$*" >>"$FIX/calls"
case $1 in
  ps) cat "$FIX/unhealthy" 2>/dev/null || true; exit 0 ;;
  restart) exit 0 ;;
  compose) ;;
  *) exit 0 ;;
esac
case " $* " in
  *" config --services "*) cat "$FIX/services" 2>/dev/null || true; exit 0 ;;
  *" exec -T db pg_dumpall "* | *" exec -T db pg_dump "*)
    [[ ! -e $FIX/dump-fails ]] || { echo "pg_dump: error: a message that must never be logged" >&2; exit 1; }
    [[ ! -e $FIX/dump-empty ]] || exit 0
    if [[ " $* " == *" pg_dumpall "* ]]; then printf -- '--\n-- PostgreSQL database cluster dump\n'; else printf 'PGDMP\001synthetic'; fi
    exit 0
    ;;
esac
while (($#)) && [[ $1 != backup ]]; do shift; done
shift
drill=$RWS_SRV/backup/drill
case $1 in
  init) ;;
  backup)
    [[ ! -e $FIX/backup-fails ]] || exit 1
    [[ ! -e $FIX/backup-unreadable ]] || exit 3
    ;;
  snapshots) printf '[{"id":"%s","time":"2026-09-02T00:00:00.123456789Z"}]\n' "$(printf 'a%.0s' {1..64})" ;;
  ls)
    # restic ls --json: the snapshot, then one node per entry.
    printf '{"struct_type":"snapshot","id":"x"}\n{"name":"_manifest","type":"dir","path":"/data/raw/_manifest"}\n'
    for f in "$FIX/raw/_manifest"/*; do
      printf '{"name":"%s","type":"file","path":"/data/raw/_manifest/%s"}\n' "${f##*/}" "${f##*/}"
    done
    ;;
  restore)
    grep '/_manifest/' "$drill/.include" >>"$FIX/restored-manifests" || true
    while IFS= read -r path; do
      src=$FIX/raw/${path#/data/raw/}
      [[ -f $src ]] || continue
      mkdir -p "$(dirname "$drill$path")"
      cp "$src" "$drill$path"
    done <"$drill/.include"
    victim=$(find "$drill/data/raw" -name '*.zst' -print -quit)
    if [[ -e $FIX/corrupt && -n $victim ]]; then printf 'x' | zstd -q -c >"$victim"; fi
    ;;
  *) exit 2 ;;
esac
STUB
cat >"$T/stubs/chown" <<'STUB'
#!/usr/bin/env bash
# Not root here: the requested owner is recorded, nothing changes.
printf 'chown %s\n' "$*" >>"$FIX/calls"
STUB
cat >"$T/stubs/date" <<'STUB'
#!/usr/bin/env bash
# `date -u +%s` answers $FIX/now when it exists; everything else is the real date.
if [[ $* == '-u +%s' && -e $FIX/now ]]; then cat "$FIX/now"; exit 0; fi
for d in /usr/bin/date /bin/date; do [[ -x $d ]] && exec "$d" "$@"; done
exit 127
STUB
chmod +x "$T/stubs"/*

# ---------------------------------------------------------------- fixtures
# A synthetic archive: 120 objects recorded before the snapshot (2026-09-02T00:00Z),
# and 5 lines recorded after it whose objects the snapshot does not have, in the
# newest manifest day; and 3 older days of 10 objects each.
mkobject() {
  local dir=$1 day=$2 i=$3 start=$4 store=$5 body sha key
  body="synthetic object $day $i $RANDOM$RANDOM"
  sha=$(printf '%s' "$body" | sha256sum | cut -d' ' -f1)
  key=$(printf 'raw/NL-1/nl-1-obs-key/%s/%06dZ-%s.zst' "${day//-//}" "$i" "${sha:0:16}")
  if ((store)); then
    mkdir -p "$(dirname "$dir/${key#raw/}")"
    printf '%s' "$body" | zstd -q -c >"$dir/${key#raw/}"
  fi
  jq -cn --arg key "$key" --arg sha "$sha" --arg start "$start" \
    '{v: 1, source: "NL-1", spec: "nl-1-obs-key", key: $key, sha256: $sha, fetched_at: {start: $start, end: $start}}'
  # a dup line (no object) must never be sampled
  jq -cn --arg sha "$sha" '{v: 1, key: null, dup_of: "x", sha256: $sha, fetched_at: {start: "2026-09-01T00:00:00Z"}}'
}
mkarchive() {
  local dir=$1 i day
  mkdir -p "$dir/_manifest"
  for i in $(seq 1 125); do
    if ((i <= 120)); then mkobject "$dir" 2026-09-01 "$i" 2026-09-01T12:00:00.000Z 1; else
      mkobject "$dir" 2026-09-01 "$i" 2026-09-02T00:05:00.000Z 0
    fi
  done >"$dir/_manifest/2026-09-01.jsonl"
  for day in 2026-08-29 2026-08-30 2026-08-31; do
    for i in $(seq 1 10); do mkobject "$dir" "$day" "$i" "${day}T12:00:00.000Z" 1; done >"$dir/_manifest/$day.jsonl"
  done
}

setup() {
  C=$(mktemp -d "$T/case.XXXX")
  mkdir -p "$C"/{state/releases/r,etc/secrets,srv/public/ops,srv/backup/drill,srv/backup/db,lock,fix}
  ln -s releases/r "$C/state/active"
  export FIX=$C/fix RWS_STATE_DIR=$C/state RWS_ETC=$C/etc RWS_SRV=$C/srv RWS_LOCK_DIR=$C/lock
  export PATH=$T/stubs:$ORIG_PATH
  cat >"$C/etc/rws.env" <<EOF
RWS_DOMAIN=rivierstanden.example
RWS_BACKUP=on
RWS_RESTIC_REPOSITORY=s3:https://s3.bucket.example/rws-raw/restic
EOF
  printf '%s\n' "$KEY" >"$C/etc/secrets/hc_ping_key"
  touch "$FIX/calls" "$FIX/pings" "$FIX/nft"
  mkarchive "$FIX/raw"
}
run() {
  rc=0
  "$bin/$1" "${@:2}" >"$C/out" 2>&1 || rc=$?
}
ops() { jq -c "$1" "$RWS_SRV/public/ops/ops.json"; }

fail() {
  echo "  FAIL: $*" >&2
  sed 's/^/  | /' "$C/out" >&2
  failures=$((failures + 1))
}
expect_rc() { [[ $rc == "$1" ]] || fail "exit $rc, expected $1"; }
expect_eq() { [[ $1 == "$2" ]] || fail "got '$1', expected '$2'"; }
expect_grep() { grep -qE -- "$1" "$2" || fail "no line matching /$1/ in ${2##*/}"; }
expect_no_grep() { ! grep -qE -- "$1" "$2" || fail "unexpected /$1/ in ${2##*/}"; }
case_() {
  labels=$((labels + 1))
  printf 'case %s\n' "$*"
}

# ---------------------------------------------------------------- cases
case_ "backups off: nothing runs, exit 0"
setup
sed -i 's/RWS_BACKUP=on/RWS_BACKUP=off/' "$RWS_ETC/rws.env"
run rws-backup
expect_rc 0
expect_grep "backups are off" "$C/out"
expect_no_grep . "$FIX/calls"

case_ "malformed repository: fails loudly"
setup
sed -i 's#^RWS_RESTIC_REPOSITORY=.*#RWS_RESTIC_REPOSITORY=s3:http://s3.bucket.example/rws#' "$RWS_ETC/rws.env"
run rws-backup
expect_rc 1
expect_grep "must look like s3:https" "$C/out"

case_ "backup: bucket addresses allowed, restic run, last_backup set, pinged"
setup
run rws-backup
expect_rc 0
expect_grep "add element inet rws backup4 \{ 192\.0\.2\.10,192\.0\.2\.11 \}" "$FIX/nft"
expect_grep "add element inet rws backup6 \{ 2001:db8::10 \}" "$FIX/nft"
expect_no_grep "::ffff:" "$FIX/nft"
expect_grep "compose .* run --rm --no-deps -T backup backup --host rws --exclude /data/raw/\.tmp --exclude \*\.json\.\[0-9\]\*\.tmp /data/raw$" "$FIX/calls"
expect_no_grep "exec -T db" "$FIX/calls"
expect_eq "$(ops 'keys')" '["disk_pct","drill","generated_at","last_backup"]'
[[ $(ops '.last_backup') =~ ^\"20[0-9]{2}- ]] || fail "last_backup not set"
expect_grep "/backup/start " "$FIX/pings"
expect_grep "/backup ok$" "$FIX/pings"
expect_no_grep "$KEY" "$FIX/calls"
[[ $(stat -c %a "$RWS_SRV/public/ops/ops.json") == 644 ]] || fail "ops.json is not 0644"

case_ "restic exit 3 (some files unreadable, snapshot saved): last_backup set, /fail files_unreadable (R2-C4)"
setup
touch "$FIX/backup-unreadable"
run rws-backup
expect_rc 0
[[ $(ops '.last_backup') =~ ^\"20[0-9]{2}- ]] || fail "last_backup not set"
expect_grep "/backup/fail files_unreadable$" "$FIX/pings"
expect_no_grep "/backup ok$" "$FIX/pings"
expect_grep "could not read some files" "$C/out"

case_ "backup failure: /fail with a fixed code, last_backup untouched"
setup
touch "$FIX/backup-fails"
run rws-backup
expect_rc 1
expect_grep "/backup/fail backup_failed$" "$FIX/pings"
[[ ! -e $RWS_SRV/public/ops/ops.json ]] || fail "ops.json written after a failed backup"

case_ "database dump (a release with db): globals and a custom-format dump, root:61003 0440, before restic, /data/db backed up, pinged ok"
setup
echo db >"$FIX/services"
d=$RWS_SRV/backup/db
printf 'left by a killed run' >"$d/.rws.dump.zZ9x0Q"
run rws-backup
expect_rc 0
expect_eq "$(head -c 5 "$d/rws.dump")" PGDMP
expect_eq "$(head -n 1 "$d/globals.sql")" --
expect_eq "$(stat -c %a "$d/rws.dump") $(stat -c %a "$d/globals.sql")" "440 440"
expect_grep "^chown 0:61003 -- $d/\.rws\.dump\.[A-Za-z0-9]{6}$" "$FIX/calls"
expect_grep "^chown 0:61003 -- $d/\.globals\.sql\.[A-Za-z0-9]{6}$" "$FIX/calls"
expect_grep "compose .* exec -T db pg_dumpall --globals-only --no-role-passwords -w -U rws_backup -l rws$" "$FIX/calls"
expect_grep "compose .* exec -T db pg_dump -Fc --no-large-objects -w -U rws_backup -d rws$" "$FIX/calls"
expect_grep "compose .* run --rm --no-deps -T backup backup --host rws .* /data/raw /data/db$" "$FIX/calls"
[[ $(grep -n 'exec -T db pg_dump -Fc' "$FIX/calls" | cut -d: -f1) -lt $(grep -n 'backup backup --host' "$FIX/calls" | cut -d: -f1) ]] ||
  fail "the dump did not run before restic"
expect_grep "/backup ok$" "$FIX/pings"
expect_no_grep "/fail" "$FIX/pings"
[[ -z $(find "$d" -name '.*' -type f) ]] || fail "a temporary or leftover dump file is still there"

case_ "database dump: once a UTC day, on the first run at or after 02:00 UTC, or when the last one is over 24 h old"
setup
echo db >"$FIX/services"
d=$RWS_SRV/backup/db
# check <now> <mtime of the last dump> <pg_dump runs expected>
check() {
  date -u -d "$1" +%s >"$FIX/now"
  rm -f "$d/rws.dump"
  printf 'PGDMP-old' >"$d/rws.dump"
  touch -d "$2" "$d/rws.dump"
  : >"$FIX/calls"
  run rws-backup
  expect_rc 0
  expect_eq "$(grep -c 'exec -T db pg_dump -Fc' "$FIX/calls") (now $1, last $2)" "$3 (now $1, last $2)"
}
check 2026-10-02T05:00:00Z 2026-10-02T02:30:00Z 0
check 2026-10-02T05:00:00Z 2026-10-01T23:00:00Z 1
check 2026-10-02T02:00:00Z 2026-10-01T02:17:00Z 1
check 2026-10-02T01:00:00Z 2026-10-01T23:00:00Z 0
check 2026-10-02T01:00:00Z 2026-10-01T00:59:00Z 1
rm "$d/rws.dump"
: >"$FIX/calls"
run rws-backup
expect_eq "$(grep -c 'exec -T db pg_dump -Fc' "$FIX/calls")" 1

case_ "database dump: waits for a running deploy (the rws-deploy lock), never beside one"
setup
echo db >"$FIX/services"
flock "$RWS_LOCK_DIR/rws-deploy.lock" bash -c "sleep 2; echo 'deploy lock released' >>'$FIX/calls'" &
sleep 0.5
run rws-backup
wait
expect_rc 0
[[ $(grep -n 'deploy lock released' "$FIX/calls" | cut -d: -f1) -lt $(grep -n 'exec -T db pg_dumpall' "$FIX/calls" | cut -d: -f1) ]] ||
  fail "the dump ran while the deploy lock was held"

case_ "database dump fails or is empty: the previous files stay, restic still runs with /data/db, /fail dump_failed, no tool output logged"
for mode in dump-fails dump-empty; do
  setup
  echo db >"$FIX/services"
  d=$RWS_SRV/backup/db
  printf 'PGDMP-previous' >"$d/rws.dump"
  printf -- '-- previous globals\n' >"$d/globals.sql"
  touch -d '2 days ago' "$d/rws.dump"
  touch "$FIX/$mode"
  run rws-backup
  expect_rc 0
  expect_eq "$(cat "$d/rws.dump")" PGDMP-previous
  expect_eq "$(cat "$d/globals.sql")" "-- previous globals"
  expect_grep "compose .* run --rm --no-deps -T backup backup --host rws .* /data/raw /data/db$" "$FIX/calls"
  expect_grep "/backup/fail dump_failed$" "$FIX/pings"
  expect_no_grep "/backup ok$" "$FIX/pings"
  [[ $(ops '.last_backup') =~ ^\"20[0-9]{2}- ]] || fail "last_backup not set"
  expect_no_grep "must never be logged" "$C/out"
  [[ -z $(find "$d" -name '.*' -type f) ]] || fail "a temporary dump file was left behind ($mode)"
done

case_ "object-lock-prune.sh: five PASS lines; a command in the bucket's <Days> never runs (R2-S1)"
setup
printf '[default]\naws_access_key_id = rws-vps\naws_secret_access_key = s3SecretNeverInArgv\n' >"$RWS_ETC/secrets/s3_credentials"
lock() { printf '<ObjectLockConfiguration><Rule><DefaultRetention><Mode>COMPLIANCE</Mode><Days>%s</Days></DefaultRetention></Rule></ObjectLockConfiguration>' "$1" >"$FIX/s3-lock"; }
lock 30
run ../tests/object-lock-prune.sh
expect_rc 0
expect_eq "$(grep -c '^PASS ' "$C/out")" 5
expect_no_grep "s3SecretNeverInArgv" "$FIX/calls"
lock "lmode[\$(touch $FIX/pwned)]"
run ../tests/object-lock-prune.sh
expect_rc 1
[[ ! -e $FIX/pwned ]] || fail "a command substitution in the bucket's <Days> ran"
expect_grep "^FAIL the bucket's default retention is COMPLIANCE, 0 days" "$C/out"

case_ "restore drill: 100 of 100, counts only, lines newer than the snapshot never sampled"
setup
run rws-restore-drill --force
expect_rc 0
expect_eq "$(wc -l <"$FIX/restored-manifests")" 3
expect_grep "^/data/raw/_manifest/2026-09-01\.jsonl$" "$FIX/restored-manifests"
expect_grep "backup ls --json a{64} /data/raw/_manifest$" "$FIX/calls"
expect_eq "$(tail -n 1 "$C/out")" "restore drill: sampled 100, matched 100"
expect_eq "$(ops '.drill | [.sampled, .matched]')" '[100,100]'
expect_grep "/restore-drill ok$" "$FIX/pings"
grep -c . "$RWS_SRV/backup/drill" >/dev/null 2>&1 || true
[[ -z $(find "$RWS_SRV/backup/drill" -mindepth 1) ]] || fail "the scratch directory was not emptied"
grep -q 'T000005Z\|2026-09-02T00:05' "$C/out" && fail "a line newer than the snapshot leaked into the output"
expect_no_grep "NL-1|nl-1" "$C/out"

case_ "restore drill: one corrupted object fails, /fail, result recorded"
setup
touch "$FIX/corrupt"
run rws-restore-drill --force
expect_rc 1
expect_eq "$(ops '.drill | [.sampled, .matched]')" '[100,99]'
expect_grep "/restore-drill/fail mismatch$" "$FIX/pings"
[[ -z $(find "$RWS_SRV/backup/drill" -mindepth 1) ]] || fail "the scratch directory was not emptied"

case_ "restore drill: too few objects before the snapshot"
setup
head -n 100 "$FIX/raw/_manifest/2026-09-01.jsonl" >"$FIX/m" && mv "$FIX/m" "$FIX/raw/_manifest/2026-09-01.jsonl"
rm "$FIX/raw/_manifest/2026-08-29.jsonl"
run rws-restore-drill --force
expect_rc 1
expect_grep "/restore-drill/fail too_few_objects$" "$FIX/pings"

case_ "restore drill: skipped when the last one is recent, unless --force"
setup
printf '{"generated_at":"x","last_backup":null,"drill":{"at":"%s","sampled":100,"matched":100},"disk_pct":null}\n' \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$RWS_SRV/public/ops/ops.json"
run rws-restore-drill
expect_rc 0
expect_grep "next one due later" "$C/out"
expect_no_grep "^docker" "$FIX/calls"

case_ "tick: disk_pct written, unhealthy containers restarted, other keys kept, a dead path unit re-armed"
setup
printf '{"generated_at":"x","last_backup":"2026-09-01T00:00:00Z","drill":null,"disk_pct":null,"extra":"dropped"}\n' \
  >"$RWS_SRV/public/ops/ops.json"
echo rws-capture-1 >"$FIX/unhealthy"
touch "$FIX/path-down"
run rws-tick
expect_rc 0
[[ $(ops '.disk_pct') =~ ^[0-9]+$ ]] || fail "disk_pct not a number"
expect_eq "$(ops '.last_backup')" '"2026-09-01T00:00:00Z"'
expect_eq "$(ops 'keys')" '["disk_pct","drill","generated_at","last_backup"]'
expect_grep "docker restart rws-capture-1" "$FIX/calls"
expect_grep "^nft -f -$" "$FIX/calls"
expect_grep "flush set inet rws resolvers4" "$FIX/nft"
expect_grep "rws-status-copy failed" "$C/out"
expect_grep "^systemctl reset-failed rws-status-copy.path rws-status-copy.service$" "$FIX/calls"
expect_grep "^systemctl start rws-status-copy.path$" "$FIX/calls"
expect_grep "rws-status-copy.path is not active: re-arming it" "$C/out"
run rws-tick
expect_eq "$(grep -c '^systemctl start' "$FIX/calls")" 1
expect_no_grep "^nft -f $RWS_ETC/nftables.conf$" "$FIX/calls"

case_ "tick: a missing firewall table is restored, loudly, before the resolvers fill its sets (R2-S4)"
setup
touch "$FIX/no-table"
run rws-tick
expect_rc 0
expect_grep "the host firewall \(table inet rws\) is missing: loading $RWS_ETC/nftables.conf" "$C/out"
expect_eq "$(grep -m 1 '^nft -f ' "$FIX/calls")" "nft -f $RWS_ETC/nftables.conf"
expect_grep "^nft -f -$" "$FIX/calls"
touch "$FIX/no-table"
run rws-tick --dry-run
expect_grep "dry-run: table inet rws is missing" "$C/out"
expect_eq "$(grep -c "^nft -f $RWS_ETC/nftables.conf$" "$FIX/calls")" 1

case_ "status copy: capture.json published 0644; a symlink, a non-contract and an oversize file refused; a copy past the cap cut off"
setup
mkdir -p "$RWS_SRV/public/status"
src=$RWS_SRV/public/status/capture.json
printf '{"generated_at":"2026-09-02T00:00:00.000Z","specs":[],"days":[],"seeds":[],"owner_specs":{"fresh":0,"total":0}}\n' >"$src"
run rws-status-copy
expect_rc 0
cmp -s "$src" "$RWS_SRV/public/ops/capture.json" || fail "the served copy differs from capture's file"
[[ $(stat -c %a "$RWS_SRV/public/ops/capture.json") == 644 ]] || fail "the served copy is not 0644"
printf '{"days":[],"generated_at":"symlink-canary","seeds":[],"specs":[]}\n' >"$C/canary.json"
rm "$src" && ln -s "$C/canary.json" "$src"
run rws-status-copy
expect_rc 1
expect_grep "not a regular file" "$C/out"
expect_no_grep "symlink-canary" "$RWS_SRV/public/ops/capture.json"
rm "$src" && echo '{"generated_at":"x","specs":[],"days":[],"seeds":[],"url":"x"}' >"$src"
run rws-status-copy
expect_rc 1
expect_grep "not the capture.json contract" "$C/out"
head -c 1048577 /dev/zero >"$src"
run rws-status-copy
expect_rc 1
expect_grep "larger than" "$C/out"
# Far past the cap (sparse, so the test itself writes nothing): the copy is killed, not completed and then refused.
rm "$src" && truncate -s 100G "$src"
run rws-status-copy
expect_rc 1
expect_grep "cannot copy" "$C/out"
[[ -z $(find "$RWS_SRV/public/ops" -name '.capture.json.*') ]] || fail "a temporary copy was left behind"

case_ "status copy: one JSON text only; an owner term or the canary is refused, never logged; no term list, no copy (R2-S7)"
setup
mkdir -p "$RWS_SRV/public/status"
src=$RWS_SRV/public/status/capture.json
good='{"days":[],"generated_at":"2026-09-02T00:00:00.000Z","owner_specs":{"fresh":0,"total":0},"seeds":[],"specs":[]}'
printf '"<script>alert(1)</script>"\n%s\n' "$good" >"$src"
run rws-status-copy
expect_rc 1
expect_grep "not the capture.json contract document" "$C/out"
for owner in '"days":[{"source":"LU-2"}]' '"days":[{"bytes":{"x":777777.777}}]' '"days":[{"source":"BE-3"}]'; do
  printf '{%s,"generated_at":"x","owner_specs":{"fresh":0,"total":0},"seeds":[],"specs":[]}\n' "$owner" >"$src"
  run rws-status-copy
  expect_rc 1
  expect_grep "names an owner-audience term \(invariant 11 tripwire\)" "$C/out"
  expect_no_grep "LU-2|777777\.777|BE-3|u002d" "$C/out"
done
[[ ! -e $RWS_SRV/public/ops/capture.json ]] || fail "a refused document was published"
mkdir "$C/bin" && cp "$bin/rws-status-copy" "$bin/rws-lib.sh" "$C/bin/"
printf '%s\n' "$good" >"$src"
rc=0
"$C/bin/rws-status-copy" >"$C/out" 2>&1 || rc=$?
expect_rc 1
expect_grep "no usable owner-term list" "$C/out"
run rws-status-copy
expect_rc 0

case_ "ops.json writer: a corrupt file is replaced, never kept"
setup
echo 'not json' >"$RWS_SRV/public/ops/ops.json"
run rws-tick
expect_rc 0
expect_eq "$(ops 'keys')" '["disk_pct","drill","generated_at","last_backup"]'

case_ "resolvers: servers from resolv.conf, the systemd stub skipped; --quiet drops the routine log line (R2-C8)"
setup
printf 'nameserver 127.0.0.53\noptions edns0\n' >"$C/stub.conf"
printf 'nameserver 192.0.2.53\nnameserver 2001:db8::53%%eth0\nnameserver 127.0.0.1\n' >"$C/real.conf"
RWS_RESOLV_CONF=$C/real.conf run rws-resolvers --dry-run
expect_rc 0
expect_grep "add element inet rws resolvers4 \{ 192\.0\.2\.53 \}" "$C/out"
expect_grep "add element inet rws resolvers6 \{ 2001:db8::53 \}" "$C/out"
expect_no_grep "127\.0\.0" "$C/out"
RWS_RESOLV_CONF=$C/real.conf run rws-resolvers
expect_grep "container DNS allowed to 1 IPv4 and 1 IPv6 resolvers" "$C/out"
RWS_RESOLV_CONF=$C/real.conf run rws-resolvers --quiet
expect_rc 0
expect_no_grep "." "$C/out"

echo "$labels cases, $failures failures"
((failures == 0))
